window.CFG = {
  title: "SNS 6종 자동화하기",
  brand: "JJ Creative 교육연구소",
  footer: "JJ Creative 교육연구소 · SNS 6종 자동화하기 · 사용설명서",
  tocFirst: "시작하기",
};

window.IMG = {
  python:   { file: "assets/img/python.jpg" },
  nodejs:   { file: "assets/img/nodejs.jpg" },
  git:      { file: "assets/img/git.jpg" },
  ffmpeg:   { file: "assets/img/ffmpeg.jpg" },
  claude:   { file: "assets/img/claude.jpg" },
  aistudio: { file: "assets/img/aistudio.jpg" },
  gcloud:   { file: "assets/img/gcloud.jpg" },
  meta:     { file: "assets/img/meta.jpg" },
  flow:     { file: "assets/img/flow.jpg" },
  github:   { file: "assets/img/github.jpg" },
  vercel:   { file: "assets/img/vercel.jpg" },
  connectors:  { file: "assets/img/connectors.png" },
  meta_apps:   { file: "assets/img/meta_apps.jpg" },
  ig_business: { file: "assets/img/ig_business.jpg" },
  yt_api:      { file: "assets/img/yt_api.jpg" },
  gcp_cred:    { file: "assets/img/gcp_cred.jpg" },
  threads_doc: { file: "assets/img/threads_doc.jpg" },
  npm_cc:      { file: "assets/img/npm_cc.jpg" },
  results:     { file: "assets/img/results.png" },
  concept:     { file: "assets/img/concept.png" },
  mask:        { file: "assets/img/mask.png" },
  ig01_permissions: { file: "assets/img/setup/ig01_permissions.jpg" },
  ig02_token_setup: { file: "assets/img/setup/ig02_token_setup.jpg" },
  ig04_roles_tester: { file: "assets/img/setup/ig04_roles_tester.jpg" },
  th01_home: { file: "assets/img/setup/th01_home.jpg" },
  th02_applist: { file: "assets/img/setup/th02_applist.jpg" },
  th02b_app_dashboard: { file: "assets/img/setup/th02b_app_dashboard.jpg" },
  th03_create_name: { file: "assets/img/setup/th03_create_name.jpg" },
  th05_usecase_pick: { file: "assets/img/setup/th05_usecase_pick.jpg" },
  th07_permissions: { file: "assets/img/setup/th07_permissions.jpg" },
  th09_token_gen: { file: "assets/img/setup/th09_token_gen.jpg" },
  th10_token_generator: { file: "assets/img/setup/th10_token_generator.jpg" },
  yt01_console_home: { file: "assets/img/setup/yt01_console_home.jpg" },
  yt02_project_create: { file: "assets/img/setup/yt02_project_create.jpg" },
  yt03_api_enable: { file: "assets/img/setup/yt03_api_enable.jpg" },
  yt04b_api_enabled_check: { file: "assets/img/setup/yt04b_api_enabled_check.jpg" },
  yt05_nav_menu: { file: "assets/img/setup/yt05_nav_menu.jpg" },
  yt06_api_menu: { file: "assets/img/setup/yt06_api_menu.jpg" },
  yt07_oauth_start: { file: "assets/img/setup/yt07_oauth_start.jpg" },
  yt09_oauth_appinfo: { file: "assets/img/setup/yt09_oauth_appinfo.jpg" },
  yt10_oauth_audience: { file: "assets/img/setup/yt10_oauth_audience.jpg" },
  yt13_clients_menu: { file: "assets/img/setup/yt13_clients_menu.jpg" },
  yt14_app_type: { file: "assets/img/setup/yt14_app_type.jpg" },
  yt16_client_created: { file: "assets/img/setup/yt16_client_created.jpg" },
  yt17_test_users: { file: "assets/img/setup/yt17_test_users.jpg" },
  yt18_test_user_added: { file: "assets/img/setup/yt18_test_user_added.jpg" },
  ig00_business_path: { file: "assets/img/setup/ig00_business_path.jpg" },
  mt01_account_steps: { file: "assets/img/setup/mt01_account_steps.jpg" },
  th04b_usecase_filter: { file: "assets/img/setup/th04b_usecase_filter.jpg" },
  th04c_portfolio_skip: { file: "assets/img/setup/th04c_portfolio_skip.jpg" },
};

window.SECTIONS = {
  accounts: {
    title: "계정 · 서비스 가입 (과정 전 사전과제)",
    count: 7,
    items: [
      { name: "Claude 요금제 — MAX 100 구독", url: "https://claude.com/pricing", type: "runapp" },
      { name: "네이버 블로그 개설", url: "https://blog.naver.com", type: "link" },
      { name: "티스토리 (카카오 계정)", url: "https://www.tistory.com", type: "link" },
      { name: "인스타그램 — 비즈니스 계정 전환", url: "https://help.instagram.com/502981923235522", type: "docs" },
      { name: "유튜브 채널 만들기", url: "https://www.youtube.com/create_channel", type: "link" },
      { name: "GitHub 가입 — 반드시 지메일 계정으로", url: "https://github.com", type: "github" },
      { name: "Vercel 가입 — GitHub 계정으로 로그인", url: "https://vercel.com/signup", type: "vercel" },
    ],
  },
  runtime: {
    title: "기본 런타임 4종 내려받기",
    count: 4,
    items: [
      { name: "Python — Windows installer 64-bit", url: "https://www.python.org/downloads/windows/", type: "docs" },
      { name: "Node.js LTS — Windows Installer (.msi)", url: "https://nodejs.org/ko/download", type: "docs" },
      { name: "Git for Windows", url: "https://git-scm.com/download/win", type: "github" },
      { name: "ffmpeg — gyan.dev full build", url: "https://www.gyan.dev/ffmpeg/builds/", type: "link" },
    ],
  },
  keys: {
    title: "API 키 · 토큰 발급처",
    count: 4,
    items: [
      { name: "Gemini API 키 — Google AI Studio", url: "https://aistudio.google.com/apikey", type: "aistudio" },
      { name: "YouTube Data API v3 사용 설정", url: "https://console.cloud.google.com/apis/library/youtube.googleapis.com", type: "link" },
      { name: "Meta 개발자 — 인스타그램 앱", url: "https://developers.facebook.com/apps/", type: "link" },
      { name: "Meta 개발자 — 스레드 API 문서", url: "https://developers.facebook.com/docs/threads", type: "docs" },
    ],
  },
  deploy: {
    title: "배포 · 이미지 호스팅",
    count: 3,
    items: [
      { name: "Vercel 가입 (GitHub 로그인)", url: "https://vercel.com/signup", type: "vercel" },
      { name: "Google Flow — 이미지 생성", url: "https://labs.google/fx/tools/flow", type: "aistudio" },
      { name: "카드뉴스 스타일 20종 대시보드", url: "https://jj-aiedu.vercel.app/style/card-styles.html", type: "vercel" },
    ],
  },
};

window.PROMPTS = {
  browserSetup: "너는 지금부터 내 **브라우저를 직접 조작해서** Meta 개발자 설정을 끝까지 도와주는 도우미다.\n나는 컴퓨터를 잘 모르는 사람이라고 생각하고, **한 번에 한 단계씩만** 진행해라.\n\n반드시 지킬 것 (어기면 안 됨)\n\n1. **내 비밀번호·인증번호는 네가 절대 입력하지 마라.**\n   로그인 화면·문자 인증 화면이 나오면 멈추고 \"여기는 직접 로그인해 주세요\"라고 말한 뒤 기다려라.\n2. **캡차(로봇이 아닙니다 / 그림 맞추기)가 나오면 네가 풀지 마라.** 나에게 넘기고 기다려라.\n3. 🔴 **액세스 토큰이 화면에 나오면 절대 읽지 마라.**\n   - 토큰 문자열을 채팅에 옮겨 적지 마라\n   - 토큰이 보이는 화면을 캡처하지 마라\n   - \"화면의 긴 문자열을 직접 복사해서 메모장에 붙여넣으세요\"라고 **안내만** 해라\n   - 이유: 채팅에 남으면 대화 기록에 영구히 남는다. 토큰은 비밀번호와 같다.\n4. **앱은 하나만 만든다.** 스레드용·인스타용을 따로 만들지 마라.\n5. 각 단계가 끝나면 **지금 화면에 무엇이 보이는지 한 줄로 알려주고**, 내가 \"다음\"이라고 하면 진행해라.\n   화면이 아래 설명과 다르면 **추측해서 클릭하지 말고** 나에게 물어봐라.\n\n순서\n\nSTEP 1 — 인스타그램이 프로페셔널(비즈니스/크리에이터) 계정인지 확인\n\n`instagram.com` 을 열고 **설정 → 비즈니스 도구 및 관리 옵션 → 비즈니스** 로 이동해라.\n\n- **「개인용 계정으로 전환」** 이 보이면 → **이미 프로페셔널 계정이다.** 그대로 STEP 2로 간다\n- **「프로페셔널 계정으로 전환」** 이 보이면 → 눌러서 전환해라. 비즈니스·크리에이터 **둘 다 괜찮다**\n- 로그인이 안 되어 있으면 나에게 로그인을 부탁해라\n\n참고로 이 방식(Instagram 로그인 API)은 **페이스북 페이지를 연결하지 않아도 된다.** 페이지를 만들라고 하는 화면이 나오면 건너뛰어라.\n\nSTEP 2 — Meta 개발자 사이트 로그인\n\n`developers.facebook.com` 을 열어라.\n\n- 로그인이 안 되어 있으면 **내가 직접 로그인**한다. 너는 기다려라\n- 개발자 계정이 처음이면 **Register → Verify account(문자 인증) → Contact info → About you** 네 단계가 나온다.\n  인증번호는 **내가 입력**한다\n- 문자가 안 오면 국가번호가 **+82 (South Korea)** 인지, 번호 맨 앞 0 을 뺐는지 확인해서 알려줘라\n\nSTEP 3 — 앱 만들기\n\n`developers.facebook.com/apps` 에서 우측 상단 **[앱 만들기]** 를 눌러라.\n\n1. **앱 이름** — `My SNS Publisher` (아무 이름이나 괜찮다)\n2. **연락처 이메일** — 자동으로 채워져 있으면 그대로 둔다\n3. **이용 사례** 단계 — 여기가 가장 중요하다\n   - 목록에 **「Threads API 액세스」** 가 안 보이면 왼쪽 **필터 기준**에서 **「콘텐츠 관리」** 를 선택해라\n   - **「Threads API 액세스」** 와 **「Instagram에서 메시지 및 콘텐츠 관리」** 를 **둘 다** 선택해라\n4. **비즈니스 포트폴리오** 화면 → **「아직 비즈니스 포트폴리오를 연결하고 싶지 않음」** 을 고르고 넘어가라\n5. 🔴 **앱 유형을 고르는 화면이 나오면 반드시 「비즈니스(Business)」 를 골라라.**\n   다른 유형을 고르면 인스타 토큰 생성기가 나오지 않는다\n6. 나머지는 기본값으로 **[다음]** 을 눌러 앱을 만들어라\n\nSTEP 4 — 스레드 권한 확인\n\n**이용 사례 → Threads API 액세스 → 권한 및 기능** 으로 가라.\n\n다음 **두 개**가 **「테스트 준비 완료」** 여야 한다. 없으면 오른쪽 **[추가]** 를 눌러라.\n\n- `threads_basic` — 모든 스레드 기능에 필요\n- `threads_content_publish` — **글을 올리는 데 반드시 필요**\n\n나머지(`threads_delete` 등)는 지금 필요 없다. 상태를 나에게 알려줘라.\n\nSTEP 5 — 스레드 테스터 등록 (토큰보다 먼저)\n\n**[앱 역할] → 역할** 로 가라.\n\n- **내 계정이 「Threads 테스터」로 들어가 있는지** 확인해라\n- 없으면 **[사람 추가]** 로 내 계정을 넣어라\n- 🔴 초대를 보낸 뒤에는 **내가 수락해야 한다.**\n  나에게 이렇게 알려줘라 — \"스레드 앱 → 설정 → 웹사이트 권한 → 초대 수락\" 을 해달라고\n- 수락이 끝나야 다음 단계에서 계정이 보인다\n\nSTEP 6 — 스레드 토큰 만들기\n\n**이용 사례 → Threads API 액세스 → 설정** 에서 아래로 내려 **「사용자 토큰 생성기」** 를 찾아라.\n\n- 목록에 **내 스레드 계정이 보이는지** 확인해라\n- 안 보이면 STEP 5의 **수락이 아직 안 된 것**이다. 되돌아가라\n- 보이면 **[액세스 토큰 생성하기]** 를 눌러라\n\n🔴 토큰이 나오면 **읽지 말고** 이렇게만 말해라:\n> \"토큰이 나왔습니다. 화면의 긴 문자열을 직접 복사해서 메모장에 붙여넣으세요. 저는 보지 않겠습니다.\"\n\n그리고 **\"이 토큰은 60일 후 만료됩니다\"** 라고 알려줘라.\n\nSTEP 7 — 인스타그램 권한과 토큰\n\n**이용 사례 → Instagram** 으로 가라.\n\n권한 네 개를 확인해라. 특히 **두 번째가 없으면 카드뉴스가 안 올라간다.**\n\n- `instagram_business_basic` — 계정 정보 읽기\n- 🔴 `instagram_business_content_publish` — **글·사진을 올리는 권한. 이게 핵심이다**\n- `instagram_business_manage_comments` — 댓글 관리\n- `instagram_business_manage_messages` — 메시지 관리\n\n그다음 왼쪽 메뉴에서 **「API 설정(Instagram 비즈니스 로그인)」** 을 찾아 들어가라.\n(화면에 따라 **「2. 액세스 토큰 생성」** 을 펼치는 형태로 보이기도 한다)\n\n- **내 인스타 계정이 보이는지** 확인해라\n  - 안 보이면 → 인스타가 **프로페셔널 계정이 아닌 것**이다. STEP 1로 돌아가라\n- 계정 옆 **[토큰 생성]** 을 눌러라\n\n🔴 여기서도 **토큰을 읽지 마라.** STEP 6과 똑같이 안내만 하고, **60일 만료**도 함께 알려줘라.\n\nSTEP 8 — 마무리 확인\n\n다 끝나면 나에게 이렇게 정리해서 알려줘라.\n\n1. 받은 토큰이 **2개**인지 (스레드 1개 + 인스타 1개)\n2. 메모장에 둘 다 저장돼 있는지 다시 확인하라고 말해라\n3. **어느 것이 스레드 것이고 어느 것이 인스타 것인지 메모장에 이름을 붙여두라**고 말해라\n   (둘 다 긴 문자열이라 나중에 구분이 안 된다)\n4. **토큰은 60일 후 만료**되므로, 그때 이 화면에서 다시 만들면 된다고 알려줘라\n5. 토큰은 나중에 `.env` 파일에 넣는다는 것, 지금은 메모장에 두면 된다는 것\n6. 토큰을 카톡·메일·채팅에 붙여넣지 말라고 한 번 더 말해라\n\n막혔을 때\n\n- 화면이 설명과 다르면 임의로 다른 경로를 찾아가지 말고 **나에게 물어봐라**\n- 어느 단계에서 왜 막혔는지 말해줘라\n- 권한 이름이 화면에 영어로 보이면 그대로 읽어서 알려줘라\n\n지금 STEP 1부터 시작해라.",
};
