window.CFG = {
  title: "SNS 6종 자동화하기",
  brand: "JJ Creative 교육연구소",
  footer: "JJ Creative 교육연구소 · SNS 6종 자동화하기 · 사용설명서",
  tocFirst: "시작하기",
};

window.IMG = {
  python:   { file: "assets/img/python.jpg" },
  nodejs:   { file: "assets/img/nodejs.jpg" },
  git:      { file: "assets/img/git.jpg" },
  ffmpeg:   { file: "assets/img/ffmpeg.jpg" },
  claude:   { file: "assets/img/claude.jpg" },
  aistudio: { file: "assets/img/aistudio.jpg" },
  gcloud:   { file: "assets/img/gcloud.jpg" },
  meta:     { file: "assets/img/meta.jpg" },
  flow:     { file: "assets/img/flow.jpg" },
  github:   { file: "assets/img/github.jpg" },
  vercel:   { file: "assets/img/vercel.jpg" },
  connectors:  { file: "assets/img/connectors.png" },
  meta_apps:   { file: "assets/img/meta_apps.jpg" },
  ig_business: { file: "assets/img/ig_business.jpg" },
  yt_api:      { file: "assets/img/yt_api.jpg" },
  gcp_cred:    { file: "assets/img/gcp_cred.jpg" },
  threads_doc: { file: "assets/img/threads_doc.jpg" },
  npm_cc:      { file: "assets/img/npm_cc.jpg" },
  results:     { file: "assets/img/results.png" },
  concept:     { file: "assets/img/concept.png" },
  mask:        { file: "assets/img/mask.png" },
  ig01_permissions: { file: "assets/img/setup/ig01_permissions.jpg" },
  ig02_token_setup: { file: "assets/img/setup/ig02_token_setup.jpg" },
  ig04_roles_tester: { file: "assets/img/setup/ig04_roles_tester.jpg" },
  th01_home: { file: "assets/img/setup/th01_home.jpg" },
  th02_applist: { file: "assets/img/setup/th02_applist.jpg" },
  th02b_app_dashboard: { file: "assets/img/setup/th02b_app_dashboard.jpg" },
  th03_create_name: { file: "assets/img/setup/th03_create_name.jpg" },
  th05_usecase_pick: { file: "assets/img/setup/th05_usecase_pick.jpg" },
  th07_permissions: { file: "assets/img/setup/th07_permissions.jpg" },
  th09_token_gen: { file: "assets/img/setup/th09_token_gen.jpg" },
  th10_token_generator: { file: "assets/img/setup/th10_token_generator.jpg" },
  yt01_console_home: { file: "assets/img/setup/yt01_console_home.jpg" },
  yt02_project_create: { file: "assets/img/setup/yt02_project_create.jpg" },
  yt03_api_enable: { file: "assets/img/setup/yt03_api_enable.jpg" },
  yt04b_api_enabled_check: { file: "assets/img/setup/yt04b_api_enabled_check.jpg" },
  yt05_nav_menu: { file: "assets/img/setup/yt05_nav_menu.jpg" },
  yt06_api_menu: { file: "assets/img/setup/yt06_api_menu.jpg" },
  yt07_oauth_start: { file: "assets/img/setup/yt07_oauth_start.jpg" },
  yt09_oauth_appinfo: { file: "assets/img/setup/yt09_oauth_appinfo.jpg" },
  yt10_oauth_audience: { file: "assets/img/setup/yt10_oauth_audience.jpg" },
  yt13_clients_menu: { file: "assets/img/setup/yt13_clients_menu.jpg" },
  yt14_app_type: { file: "assets/img/setup/yt14_app_type.jpg" },
  yt16_client_created: { file: "assets/img/setup/yt16_client_created.jpg" },
  yt17_test_users: { file: "assets/img/setup/yt17_test_users.jpg" },
  yt18_test_user_added: { file: "assets/img/setup/yt18_test_user_added.jpg" },
  ig00_business_path: { file: "assets/img/setup/ig00_business_path.jpg" },
  mt01_account_steps: { file: "assets/img/setup/mt01_account_steps.jpg" },
  th04b_usecase_filter: { file: "assets/img/setup/th04b_usecase_filter.jpg" },
  th04c_portfolio_skip: { file: "assets/img/setup/th04c_portfolio_skip.jpg" },
};

window.SECTIONS = {
  accounts: {
    title: "계정 · 서비스 가입 (과정 전 사전과제)",
    count: 7,
    items: [
      { name: "Claude 요금제 — MAX 100 구독", url: "https://claude.com/pricing", type: "runapp" },
      { name: "네이버 블로그 개설", url: "https://blog.naver.com", type: "link" },
      { name: "티스토리 (카카오 계정)", url: "https://www.tistory.com", type: "link" },
      { name: "인스타그램 — 비즈니스 계정 전환", url: "https://help.instagram.com/502981923235522", type: "docs" },
      { name: "유튜브 채널 만들기", url: "https://www.youtube.com/create_channel", type: "link" },
      { name: "GitHub 가입 — 반드시 지메일 계정으로", url: "https://github.com", type: "github" },
      { name: "Vercel 가입 — GitHub 계정으로 로그인", url: "https://vercel.com/signup", type: "vercel" },
    ],
  },
  runtime: {
    title: "기본 런타임 4종 내려받기",
    count: 4,
    items: [
      { name: "Python — Windows installer 64-bit", url: "https://www.python.org/downloads/windows/", type: "docs" },
      { name: "Node.js LTS — Windows Installer (.msi)", url: "https://nodejs.org/ko/download", type: "docs" },
      { name: "Git for Windows", url: "https://git-scm.com/download/win", type: "github" },
      { name: "ffmpeg — gyan.dev full build", url: "https://www.gyan.dev/ffmpeg/builds/", type: "link" },
    ],
  },
  keys: {
    title: "API 키 · 토큰 발급처",
    count: 4,
    items: [
      { name: "Gemini API 키 — Google AI Studio", url: "https://aistudio.google.com/apikey", type: "aistudio" },
      { name: "YouTube Data API v3 사용 설정", url: "https://console.cloud.google.com/apis/library/youtube.googleapis.com", type: "link" },
      { name: "Meta 개발자 — 인스타그램 앱", url: "https://developers.facebook.com/apps/", type: "link" },
      { name: "Meta 개발자 — 스레드 API 문서", url: "https://developers.facebook.com/docs/threads", type: "docs" },
    ],
  },
  deploy: {
    title: "배포 · 이미지 호스팅",
    count: 3,
    items: [
      { name: "Vercel 가입 (GitHub 로그인)", url: "https://vercel.com/signup", type: "vercel" },
      { name: "Google Flow — 이미지 생성", url: "https://labs.google/fx/tools/flow", type: "aistudio" },
      { name: "카드뉴스 스타일 20종 대시보드", url: "https://jj-aiedu.vercel.app/style/card-styles.html", type: "vercel" },
    ],
  },
};
