window.DECK = [
{ type:"cover", kicker:"기업교육 강사 · 컨설턴트 · HRDer 를 위한",
  title:'<span class="hl">SNS 6종 자동화</span>하기',
  subtitle:"아무것도 깔려 있지 않은 윈도우 PC 기준 &middot; A to Z 사용설명서<br>순서대로 따라만 하시면 혼자서도 끝낼 수 있습니다",
  meta:["Windows 10/11 + Claude Desktop 앱","소요 2~3시간","JJ Creative 교육연구소"] },

{ type:"artifact", sec:"00. 시연 영상", title:"먼저 보세요 — 실제 자동화 시연 (4분 16초)",
  kind:"iframe",
  src:"https://1970jjh.github.io/jj-sns-setup-handbook/media/jj-sns-demo.mp4",
  url:"강의 사진 폴더 하나 → SNS 6종 완성까지 전 과정 녹화",
  bullets:[
    {h:"스타일 선택", t:"카드뉴스 20종 중 번호 하나를 고르는 장면"},
    {h:"자동 모자이크", t:"사람 얼굴과 명찰이 자동으로 가려집니다"},
    {h:"이미지 생성 · 발행", t:"AI 가 이미지를 만들고 네이버 블로그가 스스로 발행"},
    {h:"6채널 확인", t:"완성된 여섯 채널을 하나씩 열어 확인 · 쇼츠 재생"} ],
  note:"사람이 한 일은 <b>두 가지뿐</b>입니다 — ① 사진을 폴더에 넣는다 ② 스타일 번호를 고른다. 재생이 안 되면 <a href='https://1970jjh.github.io/jj-sns-setup-handbook/media/jj-sns-demo.mp4'>이 주소</a>로 직접 열어보세요." },

{ type:"statement", topic:"claude",
  big:'사진 폴더 하나가<br><span class="hl">SNS 6종</span>이 됩니다',
  sub:"네이버 블로그 · 티스토리 · 홈페이지 · 스레드 · 인스타그램 · 유튜브 쇼츠" },

{ type:"split", sec:"00. 전체 그림", title:"완성하면 이렇게 됩니다", side:"right", img:"results",
  url:"실제 발행 결과 — 2026.08.05",
  lead:"강의 사진 폴더 하나로 여섯 채널이 자동으로 채워집니다. 아래는 실제 발행 화면입니다.",
  bullets:[
    {h:"네이버 블로그", t:"현장 사진 + 후기 원고, 얼굴·명찰 자동 모자이크"},
    {h:"티스토리 · 홈페이지", t:"검색용 문체로 다시 쓰고 교육 사례에 자동 반영"},
    {h:"스레드 · 인스타그램", t:"핵심 인사이트 / 카드뉴스 10장 캐러셀"},
    {h:"유튜브 쇼츠", t:"내레이션·자막·편집·업로드까지 전부 자동"} ],
  note:"사람이 쓰는 시간은 <b>사진 폴더 지정과 스타일 선택, 몇 분</b>이 전부입니다." },

{ type:"concept", eyebrow:"OVERVIEW", title:"무엇을 왜 설치하나",
  lead:"이 자동화는 <b>MCP 없이</b> 돌아갑니다. 아래 다섯 덩어리만 갖추면 됩니다.",
  bullets:[
    {h:"① 런타임 4종", t:"Python · Node.js · Git · ffmpeg — 스크립트와 영상 렌더의 토대"},
    {h:"② Claude Desktop + Claude Code", t:"스킬을 실행하는 본체. Windows 앱 기준"},
    {h:"③ 파이썬 패키지 7종", t:"브라우저 자동화 · 얼굴 모자이크 · TTS · 유튜브 업로드"},
    {h:"④ API 키와 토큰 4종", t:"Gemini · YouTube · 인스타그램 · 스레드"},
    {h:"⑤ 브라우저 로그인 세션 3종", t:"네이버 · 티스토리(카카오) · Google Flow"},
    {h:"⑥ 커넥터 (선택이지만 권장)", t:"GitHub · Vercel — 켜두면 배포를 Claude 가 대신합니다"} ],
  aside:{ h:"참고 — 이건 이렇습니다", items:[
    "MCP 서버 — 필요 없습니다 (0개)",
    "커넥터 — GitHub · Vercel · PlayMCP 는 켜두면 편합니다",
    "Claude in Chrome — 네이버 차단으로 사용 불가",
    "유료 이미지 API 불필요 — Flow 구독으로 0원"] } },

{ type:"table", sec:"00. 순서", title:"전체 순서 — 이 순서대로만 하시면 됩니다",
  head:["순서","무엇을","걸리는 시간"],
  rows:[
    ["<b>STEP 0</b>","계정 만들기 (Claude MAX · SNS 6종 · GitHub)","30분 · <b>과정 전에 미리</b>"],
    ["<b>STEP 1</b>","프로그램 4개 설치 (Python · Node.js · Git · ffmpeg)","20분"],
    ["<b>STEP 2</b>","Claude 앱 + Claude Code 설치, 커넥터 켜기","15분"],
    ["<b>STEP 3</b>","파이썬 부품 설치 (명령어 복사·붙여넣기)","5분"],
    ["<b>STEP 4</b>","열쇠 받기 — Gemini · 스레드 · 인스타 · 유튜브","<b>60분 · 가장 오래 걸림</b>"],
    ["<b>STEP 5</b>","네이버 · 티스토리 · Flow 로그인 한 번씩","5분"],
    ["<b>STEP 6</b>","GitHub · Vercel 연결 (인스타 발행에 필요)","10분"],
    ["<b>STEP 7</b>","스킬 3종 + 엔진 내려받아 설치","20분"],
    ["<b>끝</b>","사진 폴더 지정 → 스타일 번호 고르기","<b>이게 전부입니다</b>"] ],
  note:"💡 전부 <b>2~3시간</b> 이면 끝납니다. STEP 4(열쇠 받기)가 제일 길고 어렵습니다. 그 구간은 <b>실제 화면 27장</b>으로 하나씩 짚어드립니다. 화면 위 <b>목차</b> 를 누르면 원하는 단계로 바로 갈 수 있습니다." },

{ type:"table", sec:"00. 용어", title:"먼저 — 앞으로 나올 낯선 말 11가지",
  head:["말","쉽게 말하면","언제 나오나"],
  rows:[
    ["<b>API</b>","프로그램끼리 대화하는 <b>통로</b>. 사람이 손으로 하던 일을 프로그램이 대신하게 해줍니다","유튜브·인스타에 자동으로 올릴 때"],
    ["<b>토큰</b>","비밀번호 대신 쓰는 <b>긴 문자열 열쇠</b>. 남에게 주면 안 됩니다","인스타·스레드 연결"],
    ["<b>OAuth</b>","구글이 \"이 프로그램이 내 유튜브에 올려도 됩니다\"라고 <b>확인해주는 절차</b>","유튜브 인증"],
    ["<b>PATH</b>","명령어를 <b>어디서든 쓸 수 있게</b> 등록하는 목록","Python·ffmpeg 설치"],
    ["<b>CLI</b>","검은 창에 <b>명령어를 쳐서</b> 쓰는 방식 (Claude Code 가 이것)","Claude 설치"],
    ["<b>PowerShell</b>","윈도우의 그 <b>검은 창</b>. 명령어를 붙여넣는 곳","설치·확인할 때마다"],
    ["<b>렌더</b>","조각들을 합쳐 <b>영상 파일로 만들어내는</b> 작업","쇼츠 제작"],
    ["<b>커넥터</b>","Claude 가 외부 서비스와 연결되게 <b>켜두는 스위치</b>","GitHub·Vercel 연동"],
    ["<b>캐러셀</b>","인스타에서 <b>옆으로 넘겨보는</b> 여러 장 게시물","카드뉴스 발행"],
    ["<b>.env</b>","내 열쇠들을 적어두는 <b>메모장 파일</b>. 이 폴더 밖으로 안 나갑니다","키·토큰 저장"],
    ["<b>JSON</b>","설정을 담은 <b>텍스트 파일</b>. 열어볼 필요는 없습니다","유튜브 인증 파일"] ],
  note:"💡 지금 다 외우지 않으셔도 됩니다. 나오면 그때 이 장으로 돌아와 보시면 됩니다. <b>목차에서 '00. 용어'</b> 를 누르면 바로 옵니다." },

{ type:"chapter", topic:"claude", kicker:"STEP 0", num:"0", icon:"🪪",
  title:"계정 먼저 — 과정 전 사전과제",
  sub:"승인·심사에 시간이 걸립니다. 여기서 막히면 당일 실습을 못 따라옵니다.",
  points:["Claude MAX 100 구독","SNS 6개 채널 계정","GitHub · Vercel"] },

{ type:"gallery", sec:"00. 계정 준비", title:"계정 · 서비스 가입 (클릭하면 열립니다)",
  section:"accounts", layout:"link", max:8,
  lead:"아래 일곱 개는 <b>과정 시작 전까지</b> 반드시 끝내주세요.<br>🔴 <b>GitHub 은 지메일 계정으로</b> 가입하고, <b>Vercel 은 그 GitHub 계정으로 로그인</b>하세요 — 따로 만들면 배포가 연결되지 않습니다.",
  res:[
    { label:"⬇ 사전 준비 체크시트 (엑셀) 내려받기", url:"media/sns6-checklist.xlsx" },
    { label:"📋 사전 셋팅 안내 — 참석 전에 미리 보기", url:"https://claude.ai/code/artifact/8c51db7b-c04f-493a-bfc0-c594ce4689e1", ghost:true } ] },

{ type:"table", title:"계정 준비 체크리스트", head:["#","항목","확인 포인트"],
  rows:[
    ["0-1","<b>Claude 유료 구독 (MAX 100)</b>","실습량이 많아 Pro는 한도 초과 — 필수"],
    ["0-2","구글 계정","Gemini 키 · 유튜브 · Flow 가 전부 여기 묶임"],
    ["0-3","네이버 계정 + 블로그 개설","글쓰기 API 종료 → 브라우저 자동화"],
    ["0-4","티스토리 블로그 (카카오)","Open API 2024년 종료"],
    ["0-5","<b>인스타 — 비즈니스/크리에이터 전환</b>","개인 계정은 API 발행 불가"],
    ["0-6","스레드 계정 (인스타 연결)","토큰 생성기로 발급"],
    ["0-7","유튜브 채널 만들기","계정만 있고 채널이 없으면 업로드가 안 됨"],
    ["0-8","<b>GitHub — 지메일 계정으로 가입</b>","구글·Vercel 과 같은 메일로 묶어야 뒤에서 안 꼬임"],
    ["0-9","<b>Vercel — GitHub 계정으로 로그인</b>","따로 가입하면 저장소 연결이 안 됨 · 카드 이미지 호스팅에 필수"] ],
  note:"⚠️ 인스타를 <b>비즈니스 계정으로 전환</b>하지 않으면 카드뉴스 자동 발행이 아예 되지 않습니다. 가장 흔한 사전준비 누락입니다." },

{ type:"chapter", topic:"env", kicker:"STEP 1", num:"1", icon:"⚙️",
  title:"기본 런타임 4종 설치",
  sub:"Python · Node.js · Git · ffmpeg — 모두 Windows 설치본",
  points:["설치 시 PATH 등록 체크","설치 후 버전 확인 명령으로 검증"] },

{ type:"gallery", sec:"01. 런타임", title:"내려받기 링크 (클릭하면 열립니다)",
  section:"runtime", layout:"link", max:4,
  lead:"네 개 모두 <b>기본 옵션 그대로</b> 설치하되, Python만 첫 화면 체크박스를 꼭 눌러주세요." },

{ type:"split", title:"① Python 설치", side:"left", img:"python",
  url:"python.org/downloads/windows",
  lead:"3.11 이상이면 됩니다. 이 컴퓨터는 3.13.7로 검증했습니다.",
  bullets:[
    {h:"Windows installer (64-bit) 선택", t:"embeddable 이 아니라 installer 를 받습니다"},
    {h:"🔴 Add python.exe to PATH 체크", t:"첫 화면 아래 체크박스. 놓치면 명령어가 전부 실패합니다"},
    {h:"Install Now 클릭", t:"나머지는 기본값 그대로"} ],
  note:"확인: PowerShell에서 <b>python --version</b> → 3.11 이상이 보이면 성공" },

{ type:"split", title:"② Node.js 설치", side:"right", img:"nodejs",
  url:"nodejs.org/ko/download",
  lead:"유튜브 쇼츠 렌더 엔진(Remotion)과 Claude Code 설치에 필요합니다.",
  bullets:[
    {h:"LTS 버전 선택", t:"Current 말고 LTS. npm이 함께 설치됩니다"},
    {h:"Windows Installer (.msi)", t:"기본 옵션 그대로 Next"},
    {h:"npm 도 같이 들어옵니다", t:"별도 설치 불필요"} ],
  note:"확인: <b>node --version</b> 과 <b>npm --version</b> 이 모두 나오면 성공" },

{ type:"split", title:"③ Git for Windows 설치", side:"left", img:"git",
  url:"git-scm.com/download/win",
  lead:"홈페이지 소스를 GitHub에 올리고 Vercel로 자동 배포할 때 씁니다.",
  bullets:[
    {h:"64-bit Git for Windows Setup", t:"자동으로 다운로드가 시작됩니다"},
    {h:"설치 옵션은 전부 기본값", t:"Next 만 계속 누르면 됩니다"},
    {h:"설치 후 이름·메일 등록", t:'git config --global user.name / user.email'} ],
  note:"확인: <b>git --version</b>" },

{ type:"split", title:"④ ffmpeg 설치 (PATH 수동 등록)", side:"right", img:"ffmpeg",
  url:"gyan.dev/ffmpeg/builds",
  lead:"쇼츠 렌더와 오디오 합성에 필요합니다. 설치 관리자가 없어 압축을 직접 풀어야 합니다.",
  bullets:[
    {h:"release full 빌드 다운로드", t:"ffmpeg-release-full.7z 또는 .zip"},
    {h:"C:\\ffmpeg 로 압축 해제", t:"경로에 한글·공백이 없어야 합니다"},
    {h:"시스템 환경변수 Path 에 추가", t:"C:\\ffmpeg\\bin 을 등록한 뒤 창을 새로 엽니다"} ],
  note:"확인: <b>ffmpeg -version</b> · 이 컴퓨터는 8.1.1로 검증" },

{ type:"chapter", topic:"claude", kicker:"STEP 2", num:"2", icon:"🤖",
  title:"Claude 환경 (Windows)",
  sub:"Claude Desktop 앱 + Claude Code",
  points:["앱 설치 후 MAX 계정으로 로그인","Claude Code 는 npm 으로 설치"] },

{ type:"split", sec:"02. Claude", title:"Claude Desktop 앱 설치", side:"left", img:"claude",
  url:"claude.ai/download",
  lead:"Windows 버전을 받아 설치하고, <b>MAX 100 구독 계정</b>으로 로그인합니다.",
  bullets:[
    {h:"Download for Windows", t:"내려받아 실행하면 자동 설치됩니다"},
    {h:"MAX 구독 계정으로 로그인", t:"무료·Pro 계정이면 실습 중 한도에 걸립니다"},
    {h:"Claude Code 설치", t:"npm install -g @anthropic-ai/claude-code"} ],
  note:"설치 확인: PowerShell에서 <b>claude --version</b> → 이후 <b>claude</b> 로 실행하면 브라우저 인증이 열립니다" },

{ type:"flow", sec:"02. Claude", title:"Claude Desktop 앱 설치 직후 — 이 순서로 진행합니다",
  lead:"앱만 깔면 스킬이 바로 도는 게 아닙니다. 아래 순서를 지켜야 합니다.",
  steps:[
    {icon:"1️⃣", h:"Claude Desktop 설치", t:"claude.ai/download<br>Windows 버전"},
    {icon:"2️⃣", h:"MAX 계정 로그인", t:"앱을 열고 구독 계정으로"},
    {icon:"3️⃣", h:"Node.js 설치", t:"CLI 설치에 npm 이<br>먼저 필요합니다"},
    {icon:"4️⃣", h:"Claude Code(CLI) 설치", t:"npm install -g<br>@anthropic-ai/claude-code"},
    {icon:"5️⃣", h:"Python + ffmpeg", t:"스크립트·영상 렌더용"},
    {icon:"6️⃣", h:"커넥터 활성화", t:"GitHub · Vercel · PlayMCP"} ],
  note:"🔴 <b>순서가 중요합니다.</b> Node.js 없이 Claude Code 를 설치하려 하면 npm 명령 자체가 없어 실패합니다." },

{ type:"split", title:"Claude Code (CLI) 설치", side:"left", img:"npm_cc",
  url:"npmjs.com/package/@anthropic-ai/claude-code",
  lead:"Claude Desktop 앱과 <b>별개로</b> CLI 를 설치해야 스킬이 돌아갑니다.",
  bullets:[
    {h:"Node.js 를 먼저 설치", t:"npm 이 있어야 설치가 됩니다 (STEP 1 참고)"},
    {h:"PowerShell 에서 설치", t:"npm install -g @anthropic-ai/claude-code"},
    {h:"설치 확인", t:"claude --version 이 출력되면 성공"},
    {h:"첫 실행 시 로그인", t:"claude 입력 → 브라우저 인증 → MAX 계정 선택"} ],
  note:"앱은 대화용, CLI 는 스킬 실행용입니다. <b>둘 다 필요합니다.</b>" },

{ type:"split", title:"커넥터 활성화 — GitHub · Vercel 을 Claude 가 직접 처리", side:"right", img:"connectors",
  url:"Claude Desktop → 설정 → 커넥터",
  lead:"커넥터를 켜두면 저장소 생성·배포를 <b>Claude 가 알아서</b> 합니다. 수동 git 명령이 크게 줄어듭니다.",
  bullets:[
    {h:"설정 → 커넥터 열기", t:"좌측 메뉴 하단의 '커넥터'"},
    {h:"GitHub 연동 활성화", t:"저장소 생성·푸시를 Claude 가 수행"},
    {h:"Vercel 활성화", t:"배포와 URL 확인까지 자동"},
    {h:"PlayMCP 활성화", t:"브라우저 자동화 보조"} ],
  note:"✅ 커넥터를 켜면 STEP 6 의 GitHub·Vercel 수동 작업이 대부분 사라집니다. <b>단, 최초 계정 연결 승인은 본인이 클릭</b>해야 합니다." },

{ type:"chapter", topic:"env", kicker:"STEP 3", num:"3", icon:"📦",
  title:"파이썬 패키지 · 영상 엔진",
  sub:"명령 두 줄이면 끝납니다",
  points:["pip install 7종","playwright 브라우저 설치","npm install (Remotion)"] },

{ type:"prompts", sec:"03. 패키지", title:"복사해서 그대로 실행하세요",
  lead:"PowerShell 을 열고 아래 두 블록을 순서대로 붙여넣습니다.",
  cards:[
    { tag:"① 파이썬 패키지 + 브라우저",
      body:'<span class="v">pip install playwright pillow opencv-python numpy requests google-genai google-api-python-client google-auth-oauthlib</span><br><br><span class="v">python -m playwright install chromium</span>' },
    { tag:"② 영상 엔진 (쇼츠 렌더)",
      body:'<span class="v">cd &lt;영상작업폴더&gt;</span><br><span class="v">npm install</span><br><br>Remotion 4.x · React · TypeScript 가 함께 설치됩니다' } ] },

{ type:"table", title:"각 패키지가 하는 일", head:["패키지","쓰이는 곳"],
  rows:[
    ["<b>playwright</b>","네이버·티스토리 자동 발행, Google Flow 이미지 생성"],
    ["<b>opencv-python + numpy</b>","얼굴·명찰 자동 모자이크"],
    ["<b>pillow</b>","인스타 카드 1:1 변환, 표지 합성"],
    ["<b>google-genai</b>","Gemini TTS — 쇼츠 내레이션 음성"],
    ["<b>google-api-python-client</b><br><b>google-auth-oauthlib</b>","유튜브 업로드 인증"],
    ["<b>requests</b>","스레드·인스타 Graph API 호출"] ],
  note:"🔴 <b>python -m playwright install chromium</b> 을 빠뜨리면 브라우저 자동화가 전부 실패합니다. 가장 흔한 누락입니다." },

{ type:"chapter", topic:"gemini", kicker:"STEP 4", num:"4", icon:"🔑",
  title:"API 키 · 토큰 발급",
  sub:"여기가 가장 오래 걸립니다 — 네 가지",
  points:["Gemini 키","유튜브 OAuth","인스타 토큰","스레드 토큰"] },

{ type:"gallery", sec:"04. 키 발급", title:"발급처 바로가기",
  section:"keys", layout:"link", max:4,
  lead:"각 사이트에서 발급받아 지정된 파일에 저장합니다." },

{ type:"split", title:"① Gemini API 키", side:"left", img:"aistudio",
  url:"aistudio.google.com/apikey",
  lead:"쇼츠 내레이션 음성(TTS)을 만드는 데 씁니다.",
  bullets:[
    {h:"Google AI Studio 접속", t:"구글 계정으로 로그인"},
    {h:"API 키 만들기 클릭", t:"생성된 키를 복사"},
    {h:".env 파일에 저장", t:"GEMINI_API_KEY=복사한키"} ],
  note:"⚠️ 키는 채팅창이나 문서에 붙여넣지 마세요. .env 파일에만 둡니다." },

{ type:"split", title:"② 유튜브 업로드 인증", side:"right", img:"gcloud",
  url:"console.cloud.google.com",
  lead:"쇼츠를 자동 업로드하려면 OAuth 인증이 한 번 필요합니다.",
  bullets:[
    {h:"프로젝트 만들기", t:"이름은 자유"},
    {h:"YouTube Data API v3 사용 설정", t:"API 라이브러리에서 검색해 사용 설정"},
    {h:"OAuth 클라이언트 ID — 데스크톱 앱", t:"JSON 을 받아 사용자 폴더(C:\Users\사용자명\)에 둡니다"},
    {h:"최초 1회 브라우저 인증", t:"이후 youtube_token.pickle 로 자동 갱신"} ] },

{ type:"split", title:"③④ 인스타그램 · 스레드 토큰", side:"left", img:"meta",
  url:"developers.facebook.com",
  lead:"두 채널 모두 <b>사용자 토큰 생성기</b>로 받습니다. OAuth 구현도, 페이스북 페이지도 필요 없습니다.",
  bullets:[
    {h:"Meta 개발자에서 앱 만들기", t:"인스타그램용 · 스레드용 각각"},
    {h:"사용자 토큰 생성기에서 발급", t:"장기 토큰(60일)으로 받습니다"},
    {h:"토큰 파일로 저장", t:".auth/instagram.json · .auth/threads.json"} ],
  note:"저장 형식: <b>access_token</b> · <b>user_id</b> · <b>expires_at</b> 세 개 필드" },

{ type:"table", title:"② 유튜브 인증 — 전체 흐름 미리보기", head:["단계","화면에서 할 일","자동 여부"],
  rows:[
    ["1","<b>console.cloud.google.com</b> → 새 프로젝트 만들기","🟡 Claude 가 안내, 클릭은 본인"],
    ["2","API 라이브러리 → <b>YouTube Data API v3</b> 검색 → 사용 설정","🟡 동일"],
    ["3","OAuth 동의 화면 → 외부 → 앱 이름·이메일 입력","🔴 <b>본인 입력 필수</b>"],
    ["4","테스트 사용자에 <b>본인 구글 계정 추가</b>","🔴 누락 시 인증 거부됨"],
    ["5","사용자 인증 정보 → OAuth 클라이언트 ID → <b>데스크톱 앱</b>","🟡 안내"],
    ["6","JSON 다운로드 → <b>C:\Users\사용자명\</b> 에 저장","🟢 Claude 가 경로 안내"],
    ["7","최초 1회 브라우저 인증 → 계정 선택 → 허용","🔴 <b>본인 클릭</b>"] ],
  note:"💡 지금은 <b>흐름만</b> 눈에 익히시면 됩니다. 각 단계의 <b>실제 화면</b>은 뒤쪽 <b>'B. 유튜브 인증'</b> 구간에서 하나씩 큰 그림으로 봅니다. 4단계 테스트 사용자 추가를 빠뜨리는 사례가 가장 많습니다." },

{ type:"duo", title:"유튜브 OAuth — 실제 화면", lead:"왼쪽에서 API 를 켜고, 오른쪽에서 인증 정보를 만듭니다.",
  imgs:[
    {id:"yt_api", url:"console.cloud.google.com — YouTube Data API v3", cap:"① API 라이브러리에서 '사용 설정'"},
    {id:"gcp_cred", url:"console.cloud.google.com/apis/credentials", cap:"② 사용자 인증 정보 → OAuth 클라이언트 ID → 데스크톱 앱"} ] },

{ type:"split", title:"③ 인스타그램 토큰 — 비즈니스 전환이 먼저", side:"left", img:"ig_business",
  url:"help.instagram.com — 비즈니스 계정 전환",
  lead:"🔴 <b>개인 계정이면 여기서 막힙니다.</b> 전환 먼저 하고 토큰을 받습니다.",
  bullets:[
    {h:"1. 인스타 앱에서 전환", t:"설정 → 계정 유형 → 비즈니스/크리에이터"},
    {h:"2. Meta 개발자에서 앱 생성", t:"developers.facebook.com/apps"},
    {h:"3. 사용자 토큰 생성기", t:"장기 토큰(60일)으로 발급"},
    {h:"4. .auth/instagram.json 저장", t:"access_token · user_id · expires_at"} ],
  note:"OAuth 구현도, 페이스북 페이지도 필요 없습니다. <b>토큰 생성기 한 번</b>이면 됩니다. 실제 화면은 뒤쪽 <b>'A. 스레드·인스타'</b> 구간에서 봅니다." },
  { type:"shot", img:"ig00_business_path", title:"③-1 비즈니스 전환 — 내 계정은 어느 쪽인가",
    url:"instagram.com → 설정",
    caption:"설정 왼쪽 메뉴에서 <b>비즈니스 도구 및 관리 옵션</b> 을 누르면 오른쪽에 <b>비즈니스</b> 항목이 나옵니다.",
    steps:["인스타 왼쪽 아래 <b>☰</b> → <b>설정</b>", "<b>비즈니스 도구 및 관리 옵션</b> 클릭", "오른쪽 <b>비즈니스</b> 항목을 확인"],
    note:"🔴 여기서 <b>«개인용 계정으로 전환»</b> 이 보이면 <b>이미 비즈니스 계정</b>입니다 — 더 할 일이 없습니다.<br>반대로 <b>«프로페셔널 계정으로 전환»</b> 이 보이면 그것을 눌러 전환하세요." },

{ type:"split", title:"④ 스레드 토큰", side:"right", img:"threads_doc",
  url:"developers.facebook.com/docs/threads",
  lead:"인스타와 <b>같은 앱</b>에서 받습니다. 앱을 새로 만들지 않습니다.",
  bullets:[
    {h:"스레드 계정이 인스타와 연결돼 있어야 함", t:"미연결이면 토큰 생성 단계에서 막힙니다"},
    {h:"이용 사례 → Threads API 액세스", t:"앱 대시보드에서 이용 사례로 들어갑니다"},
    {h:"권한 확인 후 토큰 생성", t:"threads_basic · threads_content_publish 두 가지"},
    {h:"받은 토큰은 .env 에 저장", t:"PowerShell 로 넣는 방법은 뒤에서 자세히"} ],
  caption:"자세한 화면은 다음 장 <b>A. 스레드·인스타</b> 구간에서 하나씩 봅니다." },

{ type:"split", title:"Meta 개발자 — 앱은 하나만 만듭니다", side:"right", img:"meta_apps",
  url:"developers.facebook.com/apps",
  lead:"🔴 <b>앱을 두 개 만들 필요가 없습니다.</b> 앱 하나에 <b>이용 사례</b>를 두 개 붙이면 스레드·인스타를 함께 씁니다.",
  bullets:[
    {h:"앱 만들기 클릭", t:"앱 이름과 연락처 이메일만 넣으면 됩니다"},
    {h:"이용 사례에서 Threads API 액세스 선택", t:"다음 화면에서 목록으로 나옵니다"},
    {h:"인스타는 나중에 이용 사례 추가", t:"대시보드 → 이용 사례 → [이용 사례 추가]"},
    {h:"각 이용 사례에서 토큰 생성", t:"스레드·인스타 토큰을 따로 받습니다"} ],
  note:"토큰은 비밀번호와 같습니다. 채팅창·문서에 붙여넣지 말고 <b>.auth 폴더 파일</b>에만 저장하세요." },

/* ───────── 실제 화면 단계별 — 스레드 / 인스타 ───────── */
{ type:"chapter", topic:"claude", kicker:"화면으로 따라하기", num:"A", icon:"📸",
  title:"스레드 · 인스타 토큰 — 실제 화면",
  sub:"빨간 상자만 순서대로 누르시면 됩니다",
  points:["Meta 개발자 사이트 접속","앱 만들기 · 이용 사례 선택","권한 확인 후 토큰 생성"] },
  { type:"promptbox", sec:"A. 스레드·인스타", key:"browserSetup",
    title:"클로드에게 시키기 — 브라우저로 따라가기",
    boxTitle:"아래 전체를 복사해 Claude 데스크탑 앱에 붙여넣으세요",
    lead:"다음 장부터 나오는 화면들을 <b>클로드가 브라우저를 직접 열어</b> 함께 진행합니다. 오른쪽 <b>[전체 복사]</b> 를 누른 뒤 Claude 채팅창에 붙여넣으면 STEP 1 부터 시작합니다.<br>🔴 비밀번호·인증번호·캡차는 <b>본인이 직접</b> 입력합니다. 토큰이 화면에 나와도 <b>클로드는 읽지 않습니다.</b>" },
  { type:"shot", img:"mt01_account_steps", title:"⓪ Meta 개발자 계정부터 만듭니다",
    url:"developers.facebook.com",
    caption:"페이스북 계정이 있어도 <b>개발자 계정</b> 은 따로 만들어야 합니다. 네 단계로 끝납니다.",
    steps:["<b>Register</b> — 페이스북 계정으로 로그인", "<b>Verify account</b> — 문자로 온 인증번호 입력", "<b>Contact info</b> — 연락받을 이메일 확인", "<b>About you</b> — 역할을 고르면 완료"],
    note:"문자가 안 오면 국가번호를 <b>+82 (South Korea)</b> 로 두고 앞의 0 을 뺀 번호로 다시 시도하세요. 화면의 이메일은 예시라 가려 두었습니다." },

{ type:"shot", sec:"A. 스레드·인스타", img:"th01_home",
  title:"① Meta 개발자 사이트 접속",
  url:"developers.facebook.com",
  caption:"페이스북 계정으로 로그인합니다. 별도 가입은 필요 없습니다.",
  steps:["브라우저 주소창에 <b>developers.facebook.com</b> 입력", "우측 상단 <b>[로그인]</b> → 페이스북 계정 선택", "개발자 계정을 따로 만들 필요는 없습니다"],
  note:"💡 페이스북 계정이 없으면 먼저 만드셔야 합니다. 인스타·스레드가 모두 Meta 소속이라 이 계정 하나로 연결됩니다." },

{ type:"shot", img:"th02_applist", title:"② 앱 만들기",
  url:"developers.facebook.com/apps",
  caption:"우측 상단 <b>[앱 만들기]</b> 를 누릅니다.",
  steps:["로그인하면 <b>내 앱</b> 목록이 나옵니다", "우측 상단 초록색 <b>[앱 만들기]</b> 클릭", "처음이면 목록이 비어 있는 게 정상입니다"],
  note:"이미 만든 앱이 있으면 여기 카드로 표시됩니다. <b>앱은 하나만</b> 만들면 됩니다." },

{ type:"shot", img:"th03_create_name", title:"③ 앱 이름과 연락처",
  url:"앱 상세 정보 단계",
  caption:"앱 이름은 자유롭게 정하시면 됩니다. 연락처 이메일은 본인 주소가 자동으로 채워집니다.",
  steps:["<b>앱 이름</b> — 자유롭게 (예: My SNS Publisher)", "<b>연락처 이메일</b> — 본인 주소가 자동으로 채워집니다", "우측 하단 <b>[다음]</b> 클릭"],
  note:"앱 이름은 나중에 바꿀 수 있습니다. 부담 없이 지으셔도 됩니다." },

{ type:"shot", img:"th05_usecase_pick", title:"④ 이용 사례에서 Threads API 액세스 선택",
  url:"이용 사례 단계 — 가장 중요",
  caption:"🔴 여기서 <b>Threads API 액세스</b> 를 고릅니다. 인스타그램은 나중에 이용 사례를 하나 더 추가하면 됩니다.",
  steps:["목록에서 <b>Threads API 액세스</b> 찾기", "오른쪽 <b>체크박스</b> 클릭", "<b>[다음]</b> → 이후 화면은 기본값으로 진행"],
  note:"🔴 여기가 핵심입니다. 인스타그램은 앱을 만든 뒤 <b>이용 사례를 하나 더 추가</b>하면 됩니다. 앱을 두 개 만들지 마세요." },
  { type:"shot", img:"th04b_usecase_filter", title:"④-1 Threads API 가 목록에 없을 때",
    url:"앱 만들기 → 이용 사례",
    caption:"목록에 <b>Threads API 액세스</b> 가 안 보이면 왼쪽 <b>필터 기준</b> 을 확인하세요.",
    steps:["왼쪽 <b>필터 기준</b> 에서 <b>콘텐츠 관리</b> 선택", "<b>Threads API 액세스</b> 가 목록에 나타남", "체크한 뒤 <b>다음</b>"],
    note:"🔴 바로 아래 <b>Instagram에서 메시지 및 콘텐츠 관리</b> 도 함께 선택해 두세요. 앱 하나로 스레드와 인스타를 모두 처리할 수 있습니다." },
  { type:"shot", img:"th04c_portfolio_skip", title:"④-2 비즈니스 포트폴리오는 건너뜁니다",
    url:"앱 만들기 → 비즈니스",
    caption:"<b>«아직 비즈니스 포트폴리오를 연결하고 싶지 않음»</b> 을 고르고 넘어갑니다.",
    steps:["포트폴리오 선택 화면이 뜨면", "<b>아직 연결하고 싶지 않음</b> 클릭", "<b>다음</b> 으로 진행"],
    note:"개인이 쓰는 자동화에는 포트폴리오가 없어도 됩니다. 나중에 필요해지면 그때 연결하면 됩니다." },

{ type:"shot", img:"th02b_app_dashboard", title:"⑤ 앱 대시보드 — 모든 설정의 출발점",
  url:"앱을 만든 뒤 나오는 화면",
  caption:"왼쪽 <b>[이용 사례]</b> 에서 권한과 토큰을, <b>[앱 역할]</b> 에서 테스터를 설정합니다.",
  steps:["<b>[이용 사례]</b> — 권한과 토큰을 설정하는 곳", "<b>[앱 역할]</b> — 테스터를 추가하는 곳", "이 두 곳만 쓰면 됩니다"],
  note:"앱을 만들면 나오는 첫 화면입니다. 메뉴가 많아 보이지만 <b>실제로 쓰는 건 두 개</b>뿐입니다." },

{ type:"shot", img:"th07_permissions", title:"⑥ 스레드 권한 확인",
  url:"이용 사례 → Threads API → 권한 및 기능",
  caption:"<b>threads_basic</b> 과 <b>threads_content_publish</b> 가 '테스트 준비 완료' 여야 글을 올릴 수 있습니다.",
  steps:["<b>threads_basic</b> — 계정 정보 읽기", "<b>threads_content_publish</b> — 글 올리기", "둘 다 '테스트 준비 완료' 인지 확인"],
  note:"없으면 오른쪽 <b>[추가]</b> 를 눌러 넣으세요. 이 두 가지가 없으면 글이 안 올라갑니다." },

{ type:"shot", img:"th09_token_gen", title:"⑦ 스레드 앱 ID·시크릿과 토큰 생성기 위치",
  url:"이용 사례 → Threads API → 설정",
  caption:"위쪽에 앱 ID·시크릿이 있고, 아래로 내리면 <b>사용자 토큰 생성기</b> 가 있습니다.",
  steps:["좌측 메뉴에서 <b>[설정]</b> 클릭", "위쪽에 <b>앱 ID</b> 와 <b>시크릿 코드</b>", "아래로 내리면 <b>사용자 토큰 생성기</b>"],
  note:"앱 ID·시크릿은 지금 쓰지 않습니다. 필요한 건 <b>아래쪽 토큰 생성기</b>입니다." },

{ type:"shot", img:"th10_token_generator", title:"⑧ 액세스 토큰 생성하기",
  url:"사용자 토큰 생성기",
  caption:"내 스레드 계정 옆 <b>[액세스 토큰 생성하기]</b> 를 누르면 긴 문자열이 나옵니다. 그것이 토큰입니다.",
  steps:["내 스레드 계정이 목록에 보이는지 확인", "오른쪽 <b>[액세스 토큰 생성하기]</b> 클릭", "나온 긴 문자열을 <b>복사</b>"],
  note:"🔴 계정이 안 보이면 <b>[Threads 테스터 추가 또는 삭제]</b> 로 본인 계정을 넣고, <b>초대를 수락</b>해야 합니다 (스레드 앱 → 설정 → 웹사이트 권한 → 초대 수락).<br>⏳ 이 토큰은 <b>60일 후 만료</b>됩니다. 만료되면 이 화면에서 다시 만들면 됩니다." },

{ type:"shot", sec:"A. 스레드·인스타", img:"ig01_permissions",
  title:"⑨ 인스타그램 — 권한 4가지와 앱 ID",
  url:"이용 사례 → Instagram → API 설정",
  caption:"🔴 <b>instagram_business_content_publish</b> 가 있어야 글·사진이 올라갑니다. 이것 하나가 빠지면 토큰을 받아도 발행이 실패합니다.",
  steps:["이용 사례에서 <b>Instagram</b> 선택", "권한 <b>4가지</b> 확인 — 없으면 [추가]", "앱 ID·시크릿은 그대로 두면 됩니다"],
  note:"<b>instagram_business_basic</b> (계정 읽기) · 🔴 <b>instagram_business_content_publish</b> (발행 — 필수) · <b>instagram_business_manage_comments</b> · <b>instagram_business_manage_messages</b><br>페이스북 «페이지»는 연결하지 않아도 됩니다 — 이 방식(Instagram 로그인)은 페이지를 요구하지 않습니다." },

{ type:"shot", img:"ig02_token_setup", title:"⑩ 인스타 토큰 생성",
  url:"2. 액세스 토큰 생성",
  caption:"펼치면 내 계정이 보입니다. <b>[토큰 생성]</b> 을 누르면 토큰이 나옵니다.",
  steps:["<b>2. 액세스 토큰 생성</b> 을 클릭해 펼치기", "내 인스타 계정이 나오는지 확인", "<b>[토큰 생성]</b> 클릭 → 문자열 복사"],
  note:"🔴 계정이 안 보이면 인스타가 <b>비즈니스/크리에이터</b> 계정이 아닌 것입니다. 인스타 앱에서 먼저 전환하세요.<br>⏳ 이 토큰도 <b>60일 후 만료</b>됩니다. 스레드 토큰과 헷갈리지 않게 <b>메모장에 이름을 붙여</b> 저장하세요." },

{ type:"shot", img:"ig04_roles_tester", title:"⑪ 앱 역할 — 테스터 확인",
  url:"앱 역할 → 역할",
  caption:"본인 계정이 테스터로 들어가 있어야 토큰이 정상 동작합니다.",
  steps:["좌측 메뉴 <b>[앱 역할]</b> → 역할", "본인 계정이 목록에 있는지 확인", "없으면 <b>[사람 추가]</b> 로 넣기"],
  note:"테스터로 등록돼 있어야 토큰이 정상 동작합니다. 보통 앱을 만든 본인은 자동으로 들어가 있습니다." },

{ type:"prompts", sec:"A. 스레드·인스타", title:"⑫ 받은 토큰은 어떻게 보관하나",
  lead:"🔴 <b>토큰을 채팅창에 붙여넣지 마세요.</b> 대화 기록에 그대로 남습니다. <b>메모장에 잠깐 적어두었다가</b>, 엔진을 설치한 뒤 아래 방법으로 옮깁니다.",
  cards:[
    { tag:"⚠️ 먼저 — 지금은 적어만 두세요",
      body:'토큰을 넣을 <span class="v">.env</span> 파일은 <b>엔진 폴더 안</b>에 만듭니다.<br>엔진은 <b>뒤쪽 STEP 7</b> 에서 내려받습니다.<br><br>👉 지금은 받은 토큰을 <b>메모장에 임시로</b> 붙여두고,<br>　 엔진 설치 후 아래 ①②③ 을 하시면 됩니다' },
    { tag:"① PowerShell 열기 (엔진 설치 후)",
      body:'윈도우 검색창에 <span class="v">PowerShell</span> 입력 → 실행<br>엔진 폴더로 이동합니다<br><br><span class="v">cd C:\\Users\\사용자명\\claude-app\\tistory</span>' },
    { tag:"② 토큰 써넣기 — 한 줄씩",
      body:'따옴표 안만 본인 값으로 바꿉니다<br><br><span class="v">Add-Content .env \'IG_USER_ID=여기에값\'</span><br><span class="v">Add-Content .env \'IG_ACCESS_TOKEN=여기에값\'</span><br><span class="v">Add-Content .env \'THREADS_USER_ID=여기에값\'</span><br><span class="v">Add-Content .env \'THREADS_ACCESS_TOKEN=여기에값\'</span>' },
    { tag:"③ 제대로 들어갔는지 확인",
      body:'키 이름만 보여주는 안전한 확인 방법입니다<br><br><span class="v">Get-Content .env | ForEach-Object { ($_ -split \'=\')[0] }</span><br><br>다섯 줄이 나오면 성공입니다' },
    { tag:"④ 왜 이렇게 하나",
      body:'토큰은 <b>비밀번호와 같습니다</b>.<br>채팅창·메모장·카톡에 붙여넣으면 기록이 남고,<br>그 기록이 유출되면 계정이 넘어갑니다.<br><br><span class="v">.env</span> 파일은 이 폴더 밖으로 나가지 않습니다' } ] },

/* ───────── 실제 화면 단계별 — 유튜브 ───────── */
{ type:"chapter", topic:"vercel", kicker:"화면으로 따라하기", num:"B", icon:"📸",
  title:"유튜브 인증 — 실제 화면",
  sub:"셋 중 가장 단계가 많습니다. 천천히 따라오세요",
  points:["구글 클라우드 프로젝트 만들기","API 켜고 동의 화면 구성","클라이언트 ID 발급 · 테스트 사용자 추가"] },
  { type:"promptbox", sec:"B. 유튜브", key:"youtubeSetup",
    title:"클로드에게 시키기 — 유튜브 인증 전 과정",
    boxTitle:"아래 전체를 복사해 Claude 데스크탑 앱에 붙여넣으세요",
    lead:"프로젝트 만들기부터 <b>JSON 내려받기·테스트 사용자 등록</b>까지 클로드가 브라우저를 열어 함께 진행합니다. 오른쪽 <b>[전체 복사]</b> 후 Claude 채팅창에 붙여넣으면 STEP 1 부터 시작합니다.<br>🔴 구글 <b>계정 선택</b>만 조심하세요 — 유튜브 채널이 있는 계정이어야 합니다. 비밀번호·2단계 인증은 <b>본인이 직접</b> 입력합니다." },

{ type:"shot", sec:"B. 유튜브 인증", img:"yt01_console_home",
  title:"① Google Cloud 콘솔 접속",
  url:"console.cloud.google.com",
  caption:"유튜브를 쓰는 구글 계정으로 로그인합니다.",
  steps:["주소창에 <b>console.cloud.google.com</b>", "<b>유튜브를 쓰는 구글 계정</b>으로 로그인", "처음이면 약관 동의가 한 번 나옵니다"],
  note:"🔴 계정을 잘못 고르면 엉뚱한 채널에 영상이 올라갑니다. <b>내 유튜브 채널의 구글 계정</b>인지 꼭 확인하세요." },

{ type:"shot", img:"yt02_project_create", title:"② 새 프로젝트 만들기",
  url:"console.cloud.google.com/projectcreate",
  caption:"프로젝트 이름을 정하고 <b>[만들기]</b>. 회사(Workspace) 계정이면 결제 계정 선택이 추가로 나옵니다 — 개인 Gmail 은 나오지 않습니다.",
  steps:["<b>프로젝트 이름</b> 입력 (예: SNS6Auto)", "<b>[만들기]</b> 클릭", "생성까지 10~30초 걸립니다"],
  note:"회사(Workspace) 계정이면 <b>결제 계정</b> 선택이 추가로 나옵니다. 개인 Gmail 은 안 나옵니다. 프로젝트 생성은 <b>무료</b>입니다." },

{ type:"shot", img:"yt05_nav_menu", title:"③ 왼쪽 위 ☰ → API 및 서비스",
  url:"탐색 메뉴",
  caption:"메뉴가 안 보이면 화면 왼쪽 위 <b>줄 세 개(☰)</b> 아이콘을 누르세요.",
  steps:["화면 <b>왼쪽 위 ☰</b>(줄 세 개) 클릭", "메뉴에서 <b>API 및 서비스</b> 찾기", "클릭해서 들어갑니다"],
  note:"메뉴가 길어서 스크롤이 필요할 수 있습니다. <b>'API 및 서비스'</b> 라고 적힌 항목입니다." },

{ type:"shot", img:"yt06_api_menu", title:"④ 여기서 세 곳을 씁니다",
  url:"API 및 서비스",
  caption:"<b>라이브러리</b>(API 켜기) · <b>사용자 인증 정보</b>(클라이언트) · <b>OAuth 동의 화면</b>(앱 정보)",
  steps:["<b>라이브러리</b> — API 를 켜는 곳", "<b>사용자 인증 정보</b> — 클라이언트를 만드는 곳", "<b>OAuth 동의 화면</b> — 앱 정보를 넣는 곳"],
  note:"앞으로 이 세 곳을 오갑니다. 순서는 <b>동의 화면 → 라이브러리 → 사용자 인증 정보</b> 입니다." },

{ type:"shot", img:"yt03_api_enable", title:"⑤ YouTube Data API v3 — 사용",
  url:"라이브러리 → YouTube Data API v3",
  caption:"검색해서 찾은 뒤 <b>[사용]</b> 을 누릅니다.",
  steps:["라이브러리에서 <b>YouTube Data API v3</b> 검색", "검색 결과를 클릭", "파란색 <b>[사용]</b> 버튼 클릭"],
  note:"🔴 버튼을 눌렀다고 생각하고 넘어가기 쉽습니다. 반드시 <b>다음 장</b>처럼 상태를 확인하세요." },

{ type:"shot", img:"yt04b_api_enabled_check", title:"⑥ 반드시 확인 — '사용 설정됨'",
  url:"API/서비스 세부정보",
  caption:"🔴 이걸 건너뛰면 나중에 업로드에서 <b>403 오류</b>가 납니다. 실제로 가장 많이 걸리는 함정입니다.",
  steps:["화면에 <b>상태: 사용 설정됨</b> 이 보이는지 확인", "<b>[사용]</b> 버튼이 사라지고 <b>[API 사용중지]</b> 로 바뀜", "이게 보이면 정상입니다"],
  note:"🔴 이걸 건너뛰면 나중에 업로드에서 <b>403 오류</b>가 납니다. 원인이 여기라는 걸 초보자는 절대 못 찾습니다." },

{ type:"shot", img:"yt07_oauth_start", title:"⑦ OAuth 동의 화면 — 시작하기",
  url:"왼쪽 메뉴 → OAuth 동의 화면",
  caption:"처음이면 '아직 구성되지 않음' 이 뜹니다. <b>[시작하기]</b> 를 누르세요.",
  steps:["왼쪽 메뉴 <b>[OAuth 동의 화면]</b> 클릭", "'아직 구성되지 않음' 화면이 나옴", "<b>[시작하기]</b> 클릭"],
  note:"이미 설정된 프로젝트면 이 화면이 안 나옵니다. 처음 만든 프로젝트에서만 보입니다." },

{ type:"shot", img:"yt09_oauth_appinfo", title:"⑧ 앱 정보 입력",
  url:"프로젝트 구성 1단계",
  caption:"앱 이름은 자유롭게, 지원 이메일은 목록에서 본인 계정을 고릅니다.",
  steps:["<b>앱 이름</b> — 자유롭게 (예: SNS6Auto Uploader)", "<b>사용자 지원 이메일</b> — 목록에서 본인 계정 선택", "<b>[다음]</b> 클릭"],
  note:"여기 적는 앱 이름은 나중에 인증 화면에 표시됩니다. 본인만 볼 것이라 아무렇게나 지어도 됩니다." },

{ type:"shot", img:"yt10_oauth_audience", title:"⑨ 대상은 반드시 [외부]",
  url:"프로젝트 구성 2단계",
  caption:"🔴 <b>[내부]</b> 를 고르면 나중에 인증이 막힙니다. 개인 계정은 [외부] 만 보일 수도 있습니다.",
  steps:["<b>[외부]</b> 선택 ← 반드시", "<b>[다음]</b> 클릭", "연락처 이메일 입력 → 약관 동의 → 만들기"],
  note:"🔴 <b>[내부]</b> 를 고르면 나중에 인증이 막힙니다. 개인 Gmail 계정은 [외부] 만 보이는 게 정상입니다." },

{ type:"shot", img:"yt13_clients_menu", title:"⑩ 클라이언트 만들기",
  url:"왼쪽 메뉴 → 클라이언트",
  caption:"<b>[+ 클라이언트 만들기]</b> 를 누릅니다.",
  steps:["왼쪽 메뉴 <b>[클라이언트]</b> 클릭", "<b>[+ 클라이언트 만들기]</b> 클릭", "처음이면 목록이 비어 있습니다"],
  note:"동의 화면 구성이 끝나야 이 메뉴가 활성화됩니다. 앞 단계를 먼저 마치세요." },

{ type:"shot", img:"yt14_app_type", title:"⑪ 유형은 [데스크톱 앱]",
  url:"OAuth 클라이언트 ID 만들기",
  caption:"웹 애플리케이션이 아닙니다. 반드시 <b>데스크톱 앱</b> 을 고르세요.",
  steps:["<b>애플리케이션 유형</b> 드롭다운 클릭", "목록에서 <b>데스크톱 앱</b> 선택", "이름은 기본값 그대로 두고 <b>[만들기]</b>"],
  note:"🔴 <b>웹 애플리케이션</b>이 아닙니다. 잘못 고르면 인증 단계에서 오류가 납니다." },

{ type:"shot", img:"yt16_client_created", title:"⑫ JSON 다운로드 — 창 닫기 전에!",
  url:"OAuth 클라이언트 생성됨",
  caption:"🔴 이 창을 닫으면 비밀번호를 <b>다시 볼 수 없습니다</b>. 받은 파일은 엔진 폴더에 둡니다.",
  steps:["<b>[JSON 다운로드]</b> 클릭 ← 창 닫기 전에!", "받은 파일을 <b>C:\\Users\\사용자명\\</b> 으로 옮기기", "<b>[확인]</b> 눌러 창 닫기"],
  note:"🔴 이 창을 닫으면 <b>비밀번호를 다시 볼 수 없습니다</b>. 파일은 열거나 고치지 말고 그대로 옮기기만 하세요." },

{ type:"shot", img:"yt17_test_users", title:"⑬ 테스트 사용자 추가",
  url:"OAuth 동의 화면 → 대상",
  caption:"🔴 게시 상태는 <b>'테스트 중' 그대로</b> 둡니다. [앱 게시] 를 누르면 구글 검수에 걸려 업로드가 막힙니다.",
  steps:["<b>게시 상태</b>는 '테스트 중' 그대로 두기", "아래로 내려 <b>테스트 사용자</b> 찾기", "<b>[Add users]</b> 클릭 → 본인 이메일 입력 → 저장"],
  note:"🔴 <b>[앱 게시]</b> 를 누르지 마세요. 구글 검수(수 주)에 걸려 업로드가 막힙니다." },

{ type:"shot", img:"yt18_test_user_added", title:"⑭ 완료 — 본인 계정이 보이면 성공",
  url:"테스트 사용자 목록",
  caption:"비어 있으면 실행할 때 <b>403 access_denied</b> 가 납니다. 꼭 확인하세요.",
  steps:["테스트 사용자 목록에 <b>본인 이메일</b> 확인", "'사용자 1명' 으로 숫자가 올라갔는지 확인", "여기까지면 유튜브 설정 끝입니다"],
  note:"🔴 목록이 비어 있으면 실행할 때 <b>403 access_denied</b> 가 납니다. 반드시 이 화면을 보고 넘어가세요." },

{ type:"prompts", sec:"B. 유튜브 인증", title:"⑮ 받은 JSON 파일은 어디에 두나",
  lead:"다운로드 폴더에 있는 <span class=\"v\">client_secret_…json</span> 을 옮겨야 엔진이 찾습니다. <b>지금 바로 옮겨도 됩니다</b> — 엔진 폴더가 아니라 <b>내 사용자 폴더</b>라서 미리 해두면 됩니다.",
  cards:[
    { tag:"① 파일 위치 확인",
      body:'보통 여기에 받아집니다<br><span class="v">C:\\Users\\사용자명\\Downloads\\</span><br><br>파일명은 이런 모양입니다<br><span class="v">client_secret_숫자-문자열.apps.<br>googleusercontent.com.json</span>' },
    { tag:"② 이 위치로 옮기기",
      body:'<span class="v">C:\\Users\\사용자명\\</span><br>(내 사용자 폴더 바로 아래)<br><br>엔진이 이 경로에서 <span class="v">client_secret_*.json</span><br>패턴으로 파일을 찾습니다' },
    { tag:"③ 파일을 열거나 고칠 필요 없습니다 ★",
      body:'받은 파일을 <b>그대로 옮기기만</b> 하면 끝입니다.<br><br>· 메모장으로 열어볼 필요 <b>없음</b><br>· 안의 내용을 복사할 필요 <b>없음</b><br>· 이름을 바꿀 필요 <b>없음</b><br><br>엔진이 <span class="v">client_secret_*.json</span> 패턴으로 알아서 찾습니다' },
    { tag:"④ 첫 실행 — 인증 창이 열립니다",
      body:'쇼츠를 처음 만들 때 브라우저가 자동으로 열립니다<br>→ 계정 선택 → 권한 허용<br><br>한 번만 하면 이후에는 자동입니다' } ] },

{ type:"concept", eyebrow:"보안", title:"이 JSON 파일, Claude 에 첨부해도 되나요?",
  lead:"🔴 <b>안 됩니다.</b> 그리고 <b>첨부할 필요도 없습니다.</b>",
  bullets:[
    {h:"왜 안 되나", t:"파일 안에 클라이언트 시크릿(비밀번호에 해당)이 들어 있습니다. 첨부하면 그 값이 대화 기록에 그대로 남습니다"},
    {h:"토큰과 같은 원칙입니다", t:"스레드·인스타 토큰을 채팅창에 붙여넣지 않는 것과 똑같은 이유입니다"},
    {h:"첨부할 필요가 없는 이유", t:"Claude 는 파일의 내용이 아니라 위치만 알면 됩니다. 제자리에 있으면 엔진이 읽어서 인증합니다"},
    {h:"그럼 뭘 하면 되나", t:"다운로드 폴더에서 C:\\Users\\사용자명\\ 으로 옮기기만 하면 끝입니다"} ],
  aside:{ h:"이렇게 말하면 됩니다", items:[
    "❌ (파일 첨부) \"이 파일 확인해줘\"",
    "✅ \"client_secret 파일을 사용자 폴더에 옮겼어\"",
    "",
    "Claude 가 파일이 제자리에 있는지",
    "직접 확인해 알려줍니다",
    "",
    "🔴 잃어버리면 클라이언트를 새로 만들어야 합니다"] } },

{ type:"table", title:"유튜브 인증에서 만나는 화면 3가지 — 당황하지 마세요",
  head:["화면에 뜨는 것","왜 나오나","어떻게 하나"],
  rows:[
    ["<b>Google에서 확인하지 않은 앱</b><br>(앱이 확인되지 않았습니다)",
     "내가 만든 앱이라 구글 검수를 안 받았기 때문. <b>정상입니다</b>",
     "<b>[고급]</b> 클릭 → <b>[앱이름(안전하지 않음)으로 이동]</b> 클릭"],
    ["<b>이 앱은 테스트 중입니다</b>",
     "테스트 모드라서 뜨는 안내",
     "그대로 <b>[계속]</b> 을 누르면 됩니다"],
    ["<b>액세스 권한 요청</b><br>(YouTube 동영상 업로드)",
     "업로드 권한을 달라는 요청",
     "체크한 뒤 <b>[계속]</b>. 이걸 허용해야 쇼츠가 올라갑니다"] ],
  note:"🔴 '확인되지 않은 앱' 경고를 보고 겁이 나서 창을 닫는 분이 많습니다. <b>내가 만든 내 앱</b>이니 안전합니다. [고급] 을 눌러 계속 진행하세요." },

{ type:"table", title:"인증은 언제 다시 해야 하나 — 만료 주기",
  head:["대상","유효기간","만료되면"],
  rows:[
    ["<b>유튜브 (테스트 모드)</b>","<b>약 7일</b>","브라우저 인증 창이 다시 열립니다. 한 번 로그인하면 또 7일"],
    ["<b>인스타그램 토큰</b>","60일","토큰 생성기에서 다시 발급 → .env 교체"],
    ["<b>스레드 토큰</b>","60일","인스타와 동일"],
    ["<b>티스토리 (카카오)</b>","주기적","작업 중 창이 뜨면 로그인만"],
    ["<b>네이버</b>","거의 안 끊김","최초 1회 로그인으로 충분"],
    ["<b>Google Flow</b>","약 8시간","Claude 에게 \"flow 로그인 다시 해줘\"" ] ],
  note:"유튜브 7일 제한은 <b>테스트 모드의 정상 동작</b>입니다. 매일 쓰시면 거의 못 느끼고, 오랜만에 쓸 때 한 번 인증하면 됩니다. [앱 게시]로 바꾸면 이 제한은 없어지지만 구글 검수(수 주)를 받아야 하므로 권하지 않습니다." },

{ type:"concept", eyebrow:"AUTOMATION BOUNDARY", title:"어디까지 Claude 가 하고, 어디부터 본인이 하나",
  lead:"토큰 발급은 <b>보안상 100% 자동이 불가능</b>합니다. 경계를 분명히 알아두세요.",
  bullets:[
    {h:"🟢 Claude 가 하는 것", t:"페이지 열기, 어디를 눌러야 하는지 안내, 발급받은 값을 올바른 파일·형식으로 저장, 연결 테스트"},
    {h:"🔴 본인이 해야 하는 것", t:"로그인, 비밀번호 입력, 2단계 인증, 약관·권한 동의 클릭, 계정 선택"},
    {h:"왜 그런가", t:"AI 가 비밀번호를 대신 입력하지 않는 것은 안전장치입니다. 계정 탈취 위험을 원천 차단합니다"} ],
  aside:{ h:"진행 방식", items:[
    "Claude 가 브라우저 창을 띄웁니다",
    "\"여기서 로그인해 주세요\" 안내",
    "본인이 로그인·동의 클릭",
    "그 다음은 다시 전부 자동",
    "→ 영상에서 본 티스토리 로그인과 같은 패턴"] } },

{ type:"chapter", topic:"wrap", kicker:"STEP 5", num:"5", icon:"🔐",
  title:"브라우저 로그인 세션",
  sub:"API 가 없는 채널은 로그인 세션을 저장해 씁니다",
  points:["네이버 — API 2020년 종료","티스토리 — API 2024년 종료","Flow — 8시간마다 갱신"] },

{ type:"table", sec:"05. 로그인", title:"세 곳의 로그인 세션",
  head:["대상","저장 위치","재로그인 주기"],
  rows:[
    ["<b>네이버</b>","~/.claude/.naver-profile","드묾"],
    ["<b>티스토리 (카카오)</b>",".auth/chrome-profile","<b>주기적으로 필요</b>"],
    ["<b>Google Flow</b>","~/.claude/.image-flow-profile","약 8시간"] ],
  note:"🔴 로그인은 <b>본인이 직접</b> 창에서 합니다. AI 는 아이디·비밀번호를 대신 입력하지 않습니다. 창이 뜨면 로그인만 해주시면 그 다음은 다시 전부 자동입니다." },

{ type:"prompts", title:"최초 1회 로그인 — 미리 해둡니다",
  lead:"첫 실행 전에 세 곳을 한 번씩 로그인해 두면 작업 도중 멈추지 않습니다.",
  cards:[
    { tag:"① 네이버 (최초 1회)",
      body:'<span class="v">python ~/.claude/skills/naver-blog-post/scripts/naver_login.py</span><br>한 번 해두면 <b>거의 안 끊깁니다</b>' },
    { tag:"② 티스토리 · 카카오 (주기적)",
      body:'엔진 폴더에서 <span class="v">python src/login.py</span><br><b>\'로그인 상태 유지\'</b> 체크를 꼭 하세요' },
    { tag:"③ Google Flow (약 8시간)",
      body:'<span class="v">python ~/.claude/skills/image-flow/scripts/flow_login.py</span><br>만료되면 Claude 에게 <b>"flow 로그인 다시 해줘"</b>' },
    { tag:"🔴 로그인은 본인이 직접",
      body:'AI 는 아이디·비밀번호를 <b>대신 입력하지 않습니다</b>.<br>작업 중 만료되면 창이 자동으로 열립니다 → <b>로그인만</b> 하시면 이어서 진행됩니다' } ] },

{ type:"chapter", topic:"vercel", kicker:"STEP 6", num:"6", icon:"🚀",
  title:"배포 · 이미지 호스팅",
  sub:"인스타 발행에 반드시 필요합니다",
  points:["GitHub 저장소","Vercel 자동 배포","Flow 이미지 생성"] },

{ type:"split", sec:"06. 배포", title:"Vercel 이 왜 필요한가", side:"right", img:"vercel",
  url:"vercel.com",
  lead:"인스타그램은 <b>https 공개 URL 이미지만</b> 받습니다. 내 PC 안의 파일로는 발행이 되지 않습니다.",
  bullets:[
    {h:"GitHub 저장소 생성 후 clone", t:"홈페이지 소스를 담습니다"},
    {h:"Vercel 에 GitHub 로그인으로 연결", t:"푸시하면 자동 배포"},
    {h:"카드 10장이 여기 올라갑니다", t:"그래야 인스타 캐러셀 발행이 성공합니다"} ],
  note:"✅ <b>커넥터를 켜두셨다면</b> 저장소 생성·연결·배포를 Claude 가 대신합니다(STEP 2 참고). 이미지가 배포되기 전에 발행하면 원인 없이 실패하니 배포 완료를 확인한 뒤 발행합니다." },

{ type:"gallery", title:"배포 · 이미지 생성 링크",
  section:"deploy", layout:"link", max:3,
  lead:"Google Flow 는 <b>구독제</b>라 이미지 생성 비용이 들지 않습니다." },

{ type:"chapter", topic:"claude", kicker:"STEP 7", num:"7", icon:"🧩",
  title:"스킬 설치와 첫 실행",
  sub:"두 스킬은 반드시 세트로",
  points:["스킬 2개 + image-flow","점검 명령 3줄","실전 호출"] },

{ type:"concept", sec:"07. 스킬", eyebrow:"IMPORTANT", title:"필요한 것은 두 덩어리입니다",
  lead:"스킬만 있으면 안 됩니다. <b>엔진(스크립트 본체)</b>이 함께 있어야 실행됩니다.",
  bullets:[
    {h:"① 엔진 폴더", t:"실제 동작하는 파이썬 스크립트 모음 — 수집·모자이크·발행·카드조립·쇼츠빌드"},
    {h:"② 스킬 폴더 3종", t:"Claude 에게 '어떤 순서로 무엇을 하라'고 알려주는 지시서"},
    {h:"③ 작업 폴더", t:"그날 찍은 사진 + 교안 파일을 넣는 곳. 매 강의마다 새로 만듭니다"},
    {h:"바로 내려받으실 수 있습니다", t:"다음 슬라이드의 링크에서 스킬·엔진 압축 파일을 받습니다"} ],
  aside:{ h:"엔진 폴더 안에 있는 것", items:[
    "src/ — 수집·발행·동기화 스크립트",
    "scripts/ — 배치·재시도 도구",
    ".auth/ — 토큰과 로그인 세션 (본인 것)",
    ".env — API 키 (본인 것)",
    "posts/ · work/ · thumbs/ — 산출물"] } },
  { type:"promptbox", sec:"05. 스킬 설치", key:"install1",
    title:"① 클로드에게 시키기 — 내려받아 제자리에 놓기",
    boxTitle:"아래 전체를 복사해 Claude 데스크탑 앱에 붙여넣으세요",
    lead:"먼저 <b>C:\sns-auto</b> 폴더를 만들고, 스킬 3종과 엔진을 받아 제자리에 놓습니다.<br>이 폴더를 <b>프로젝트 폴더로 지정</b>해 내일 실습을 진행합니다 — 경로에 한글·공백이 없어 사고가 나지 않습니다." },
  { type:"promptbox", sec:"05. 스킬 설치", key:"install2",
    title:"② 클로드에게 시키기 — 내 정보로 바꾸기 ★",
    boxTitle:"①이 끝난 뒤 이어서 붙여넣으세요",
    lead:"🔴 <b>이 단계를 건너뛰면 안 됩니다.</b> 받은 스킬·엔진에는 만든 사람의 회사명·홈페이지 주소가 그대로 들어 있습니다.<br>그대로 쓰면 <b>내 유튜브 영상 제목에 남의 회사명</b>이 붙고, <b>인스타 카드가 남의 홈페이지</b>를 가리켜 발행이 실패합니다." },
  { type:"promptbox", sec:"05. 스킬 설치", key:"install2a",
    title:"②-1 홈페이지가 깃허브·버셀에 있는 경우",
    boxTitle:"내 홈페이지를 카드 이미지 저장소로 연결합니다",
    lead:"이미 운영 중인 홈페이지 저장소를 <b>엔진 옆에</b> 내려받고, 엔진이 그 폴더를 보도록 3곳을 고칩니다.<br>마지막에 <b>시험 이미지 한 장</b>으로 주소가 실제로 열리는지 확인합니다 — 이게 열려야 인스타 발행이 됩니다." },
  { type:"promptbox", sec:"05. 스킬 설치", key:"install2b",
    title:"②-2 홈페이지가 없는 경우 ★",
    boxTitle:"인스타용 «이미지 창고» 저장소를 새로 만듭니다",
    lead:"🔴 홈페이지가 없어도 <b>인스타 발행에는 깃허브·버셀이 필요합니다.</b> 인스타 API 가 <b>공개 https 주소로 된 이미지만</b> 받기 때문입니다 — 내 컴퓨터 안의 파일은 쓸 수 없습니다.<br>사람이 볼 웹사이트가 아니라 <b>이미지 주소만 만들어 주는 창고</b>를 하나 만듭니다. 티스토리·네이버·스레드·유튜브는 이것 없이도 됩니다." },
  { type:"promptbox", sec:"05. 스킬 설치", key:"install3",
    title:"③ 앱 재시작 후 — 잘 등록됐는지 확인",
    boxTitle:"앱을 껐다 켠 뒤 붙여넣으세요",
    lead:"스킬은 <b>앱을 다시 켜야</b> 인식됩니다. 창만 닫지 말고 <b>트레이(∧) → Claude 우클릭 → 종료</b> 까지 해야 합니다.<br>다시 켠 뒤 프로젝트 폴더를 <b>C:\sns-auto</b> 로 지정하고 이 프롬프트로 확인합니다." },

{ type:"prompts", sec:"07. 스킬", title:"내려받기 — 스킬 3종 · 엔진",
  lead:"아래 두 압축 파일을 받아 압축을 푸세요. <b>스킬 먼저, 엔진 다음</b> 순서입니다.",
  cards:[
    { tag:"① 스킬 3종 (4.0MB)",
      body:'<a href="https://1970jjh.github.io/jj-sns-setup-handbook/media/jj-creative-skills.zip"><b>jj-creative-skills.zip 내려받기</b></a><br>→ <span class="v">C:\\Users\\사용자명\\.claude\\skills\\</span> 에 품니다<br>스킬 3폴더 + README-먼저읽으세요.md' },
    { tag:"② 엔진 (0.1MB)",
      body:'<a href="https://1970jjh.github.io/jj-sns-setup-handbook/media/jj-creative-engine.zip"><b>jj-creative-engine.zip 내려받기</b></a><br>→ <span class="v">C:\\Users\\사용자명\\claude-app\\tistory\\</span> 에 품니다<br>tistory/ 메인 엔진 + shorts-remotion/ 쇼츠 전용' },
    { tag:"③ 압축을 푼 뒤 — 꼭 하실 것 ★",
      body:'스킬 안의 <span class="v">YOUR_</span> 자리표시자를 본인 것으로 바꿉니다.<br>Claude 에게 이렇게 말하면 끝납니다.<br><span class="v">~/.claude/skills 안의 YOUR_ 를 내 정보로 바꿔줘</span><br><br>🔴 특히 <span class="v">naver-blog-post\\scripts\\naver_common.py</span> 6번째 줄<br><span class="v">BLOG_ID = "YOUR_NAVER_BLOG_ID"</span><br>여기가 틀리면 글이 <b>엉뚱한 블로그로</b> 갑니다' },
    { tag:"④ 패키지 설치 (2~3분)",
      body:'엔진 폴더에서<br><span class="v">pip install -r requirements.txt</span><br><span class="v">python -m playwright install chromium</span>' } ] },

{ type:"prompts", title:"폴더 배치와 .env 만들기",
  lead:"엔진을 받은 뒤 아래 두 가지를 준비하면 실행 준비가 끝납니다.",
  cards:[
    { tag:"① 권장 폴더 배치",
      body:'<span class="v">C:\Users\사용자명\claude-app\tistory\</span> ← 엔진<br><span class="v">C:\Users\사용자명\.claude\skills\</span> ← 스킬 3폴더<br><br>경로에 <b>한글·공백</b>이 없는 편이 안전합니다' },
    { tag:"② .env 파일 만들기",
      body:'메모장을 열고 아래를 입력한 뒤<br>파일명을 <span class="v">.env</span> 로 저장 (엔진 폴더에)<br><br><span class="v">GEMINI_API_KEY=발급받은키</span><br><span class="v">TTS_ENGINE=gemini</span><br><br>⚠️ 확장자가 <b>.env.txt</b> 가 되지 않도록 주의' } ] },

{ type:"concept", eyebrow:"SKILLS", title:"스킬 폴더 구조",
  lead:"<b>~/.claude/skills/</b> 아래에 세 폴더를 넣습니다.",
  bullets:[
    {h:"naver-blog-post", t:"스킬 ① — 사진 선별 · 모자이크 · 원고 · 네이버 발행"},
    {h:"tistory-thread-insta-hp-youtube", t:"스킬 ② — 티스토리 · 홈페이지 · 스레드 · 인스타 · 쇼츠"},
    {h:"image-flow", t:"두 스킬이 공통으로 호출하는 이미지 생성 엔진"} ],
  aside:{ h:"반드시 세트로", items:[
    "카드뉴스 스타일 20종 레시피가 ②에 들어 있고",
    "①이 그것을 참조합니다",
    "하나만 설치하면 스타일이 적용되지 않습니다",
    "스타일 대시보드는 웹 URL 이라 설치 불필요"] } },

{ type:"concept", eyebrow:"OPTIONAL", title:"Remotion 설치 — 유튜브 쇼츠를 만들 분만",
  lead:"쇼츠를 안 만드셔도 <b>나머지 5개 채널은 정상 동작</b>합니다. 쇼츠가 필요할 때만 하세요.",
  bullets:[
    {h:"Remotion 이 무엇인가", t:"영상을 코드로 만드는 도구. 자막·음성·장면 전환을 붙여 1080×1920 세로 영상을 뽑습니다"},
    {h:"GitHub 에서 따로 받지 않습니다", t:"엔진 압축의 shorts-remotion 폴더에서 npm install 한 번이면 알아서 내려받습니다"},
    {h:"Node.js 가 먼저 있어야 합니다", t:"node -v 로 확인. 버전이 안 나오면 STEP 1 의 Node.js 설치부터"},
    {h:"유튜브가 자동으로 쇼츠 분류", t:"세로 + 60초 이내면 쇼츠가 됩니다. 엔진이 렌더 전에 길이를 미리 검사합니다"} ],
  aside:{ h:"설치 — 마음의 준비를 하고", items:[
    "cd shorts-remotion 폴더",
    "npm install",
    "5~10분 걸립니다 (멈춘 듯해도 정상)",
    "500MB~1GB 가 생깁니다",
    "warn 경고는 괜찮고 error 만 아니면 됩니다",
    "확인 — npx remotion studio",
    "ShortsVideo 항목이 보이면 성공"] } },

{ type:"concept", sec:"07. 스킬", eyebrow:"헷갈리기 쉬움", title:"앱 설정에 스킬이 안 보입니다 — 정상입니다",
  lead:"Claude Desktop <b>앱</b>과 Claude <b>Code(CLI)</b>는 스킬을 두는 곳이 다릅니다.",
  bullets:[
    {h:"앱 설정 → 스킬 목록에는 안 나옵니다", t:"거기는 앱에 직접 업로드한 스킬만 보여줍니다. 우리 스킬 3개는 폴더에 두는 방식이라 표시되지 않습니다"},
    {h:"확인은 PowerShell 에서", t:"claude 실행 후 대화창에 슬래시 하나만 치면 목록이 펼쳐집니다. 거기서 세 개가 보이면 정상입니다"},
    {h:"왜 앱에 올리지 않나", t:"이 스킬들은 파이썬을 실행하고 브라우저를 조작합니다. 앱 대화창은 그런 일을 못 합니다"},
    {h:"앱에 올려도 소용없습니다", t:"목록에만 뜨고 실행은 안 됩니다. 폴더에 두는 것이 맞습니다"} ],
  aside:{ h:"확인 순서", items:[
    "작업표시줄에서 PowerShell 실행",
    "cd C:\\Users\\사용자명\\claude-app\\tistory",
    "claude",
    "대화창에 슬래시 한 글자만 입력",
    "",
    "naver-blog-post",
    "tistory-thread-insta-hp-youtube",
    "image-flow",
    "",
    "이 셋이 보이면 설치 성공입니다"] } },

{ type:"prompts", title:"설치 점검 · 첫 실행",
  lead:"아래를 순서대로 확인한 뒤, 사진 폴더를 만들고 스킬을 부릅니다.",
  cards:[
    { tag:"① 점검 3줄",
      body:'<span class="v">python -m playwright install chromium</span><br><span class="v">ffmpeg -version</span><br><span class="v">claude --version</span>' },
    { tag:"② 실전 호출 — 이게 전부입니다",
      body:'작업 폴더에 <b>그날 찍은 사진 + 교안 파일</b>을 넣고<br><br><span class="v">/naver-blog-post</span><br><span class="v">/tistory-thread-insta-hp-youtube</span><br><br>나머지는 전부 자동입니다' } ] },

{ type:"chapter", topic:"research", kicker:"TROUBLE", num:"8", icon:"🚨",
  title:"자주 나는 오류와 대처",
  sub:"실제로 겪은 것들만 모았습니다",
  points:["설치 단계","실행 단계","발행 단계"] },

{ type:"table", sec:"08. 오류 대처", title:"설치 · 실행 단계",
  head:["증상","원인","해결"],
  rows:[
    ["<b>'python' 은(는) 인식할 수 없는 명령</b>","설치 시 PATH 체크 누락","Python 재설치하며 <b>Add to PATH</b> 체크"],
    ["<b>브라우저가 안 열림 / Executable doesn't exist</b>","크로미움 미설치","<b>python -m playwright install chromium</b>"],
    ["<b>ffmpeg 를 찾을 수 없음</b>","Path 미등록","환경변수 Path 에 <b>C:\\ffmpeg\\bin</b> 추가 후 창 새로 열기"],
    ["<b>npm install 실패</b>","Node 미설치 또는 구버전","Node.js <b>LTS</b> 재설치"],
    ["<b>한도 초과 안내</b>","Pro 요금제 사용","<b>MAX 100</b> 으로 상향"],
    ["<b>스킬이 목록에 안 보임</b>","폴더를 한 겹 더 감쌌거나 Claude 재시작 안 함","<b>skills\\naver-blog-post\\SKILL.md</b> 구조 확인 후 Claude Code 재시작"] ],
  note:"💡 대부분은 <b>PATH 등록</b>과 <b>창을 새로 열지 않은 것</b>이 원인입니다. 환경변수를 바꿨다면 <b>PowerShell 창을 껐다 다시 여세요</b> — 열려 있던 창은 옛 설정을 그대로 씁니다." },

{ type:"table", sec:"08. 오류 대처", title:"엔진 · 토큰 단계 — 실제로 겪은 오류",
  head:["화면에 뜨는 메시지","무슨 뜻인가","해결"],
  rows:[
    ["<b>ModuleNotFoundError: No module named 'PIL'</b>","필요한 부품이 아직 안 깔림","엔진 폴더에서 <b>pip install -r requirements.txt</b>"],
    ["<b>FileNotFoundError: src/publish.py</b>","엔진 폴더 위치가 스킬에 적힌 경로와 다름","엔진을 <b>C:\\Users\\사용자명\\claude-app\\tistory\\</b> 로 옮기기"],
    ["<b>GEMINI_API_KEY 관련 오류</b>","<b>.env</b> 가 없거나 <b>.env.txt</b> 로 저장됨",'메모장 저장 시 파일명을 <b>".env"</b> 처럼 따옴표로 감싸기'],
    ["<b>403 ... API has not been used</b>","유튜브 API 를 안 켬 <b>(가장 흔함)</b>","Cloud 콘솔에서 <b>상태: 사용 설정됨</b> 확인"],
    ["<b>403 access_denied</b>","테스트 사용자에 내 계정이 없음","OAuth 동의 화면 → 대상 → <b>Add users</b>"],
    ["<b>이 앱은 Google에서 확인하지 않았습니다</b>","내가 만든 앱이라 정상","<b>[고급]</b> → <b>[앱이름(안전하지 않음)으로 이동]</b>"],
    ["<b>일주일 뒤 갑자기 인증 창이 뜸</b>","테스트 모드 7일 만료 (정상)","한 번 로그인하면 또 7일 갑니다"],
    ["<b>client_secret 파일을 찾을 수 없습니다</b>","JSON 이 아직 다운로드 폴더에 있음","<b>C:\\Users\\사용자명\\</b> 으로 옮기기 (열거나 고치지 말 것)"] ],
  note:"🔴 초보자가 가장 많이 막히는 건 <b>403 두 가지</b>입니다. 원인(API 미활성·테스트 사용자 누락)과 증상(업로드 실패)이 멀리 떨어져 있어 스스로 찾기 어렵습니다. 이 표를 그대로 보시면 됩니다." },

{ type:"table", title:"발행 단계", head:["증상","원인","해결"],
  rows:[
    ["<b>카카오 로그인 세션이 만료되었습니다</b>","티스토리 세션 만료 (정상 동작)","창이 뜨면 <b>직접 로그인</b> → 자동 재시도"],
    ["<b>Flow 에서 이미지가 0장</b>","세션 만료 또는 레이트 리밋","재로그인 · 간격 두고 재시도 (하루 40장 초과 시 발생)"],
    ["<b>인스타 발행이 원인 없이 실패</b>","이미지가 아직 배포 전","Vercel 배포 완료 확인 후 재발행"],
    ["<b>인스타 API 오류 (계정)</b>","개인 계정","<b>비즈니스/크리에이터</b> 로 전환"],
    ["<b>쇼츠가 60초를 넘습니다</b>","내레이션이 김 (검증기가 렌더 전 차단)","문장을 줄이면 자동 재계산"],
    ["<b>티스토리 발행이 조용히 실패</b>","일일 공개 발행 15건 초과","다음 날 자동 이어서 발행됨"] ],
  note:"대부분은 <b>스킬이 렌더·발행 전에 먼저 잡아내</b> 시간 낭비 없이 멈춥니다." },

{ type:"split", sec:"09. 운영 원칙", title:"개인정보는 자동으로 가려집니다", side:"left", img:"mask",
  url:"자동 모자이크 결과",
  lead:"블로그에 쓸 사진만 골라 <b>얼굴·명찰·기관 로고</b>를 자동으로 가립니다.",
  bullets:[
    {h:"얼굴 자동 검출", t:"정면·측면 모두 탐지해 모자이크 처리"},
    {h:"목걸이 명찰", t:"실명이 적힌 명찰도 함께 가립니다"},
    {h:"검수 시트 자동 생성", t:"놓친 곳이 있는지 눈으로 확인할 수 있게 표시"},
    {h:"고객사명은 익명 처리", t:"본문에서도 K사·S사 로 자동 변환"} ],
  note:"완벽하지 않을 수 있어 <b>발행 전 검수 단계</b>가 들어 있습니다. 놓친 부분은 좌표를 지정해 추가로 가릴 수 있습니다." },

{ type:"concept", eyebrow:"보안 — 꼭 지켜주세요", title:"채팅창에 넣지 말아야 할 것 3가지",
  lead:"AI 대화 기록에 남으면 <b>지워도 복구되지 않습니다</b>. 아래 셋은 절대 붙여넣지 마세요.",
  bullets:[
    {h:"① 토큰 (인스타 · 스레드)", t:"긴 문자열 열쇠입니다. PowerShell 로 .env 파일에 직접 씁니다"},
    {h:"② client_secret JSON 파일", t:"첨부도 안 됩니다. 파일을 옮기기만 하면 Claude 가 알아서 찾습니다"},
    {h:"③ 비밀번호 · API 키", t:"로그인 창이 뜨면 본인이 직접 입력합니다. AI 는 대신 입력하지 않습니다"} ],
  aside:{ h:"이렇게 하시면 안전합니다", items:[
    "✅ \"토큰을 .env 에 넣었어\"",
    "✅ \"client_secret 파일 옮겨뒀어\"",
    "✅ \"로그인 창 떠서 내가 로그인했어\"",
    "",
    "❌ 값을 그대로 붙여넣기",
    "❌ JSON 파일 첨부하기",
    "",
    "🔴 실수로 넣었다면 → 해당 키·토큰을",
    "　 즉시 폐기하고 새로 발급받으세요"] } },

{ type:"concept", eyebrow:"IMPORTANT", title:"솔직하게 알려드릴 것",
  lead:"과정에서 반복해 강조하는 세 가지입니다.",
  bullets:[
    {h:"완전 무인은 아닙니다", t:"티스토리 카카오 세션과 Flow 세션은 주기적으로 재로그인이 필요합니다"},
    {h:"하루 1건이 원칙입니다", t:"몰아서 올리면 검색엔진이 스팸으로 보고 계정이 막힙니다"},
    {h:"초기 설정에 하루를 씁니다", t:"한 번 잡아두면 그 다음부터는 사진 폴더 지정과 스타일 선택뿐입니다"} ],
  aside:{ h:"MCP 는 쓰지 않습니다", items:[
    "MCP 서버 0개 · 커넥터 0개로 동작",
    "Playwright 는 파이썬 라이브러리",
    "Claude in Chrome 은 네이버 차단으로 불가",
    "참여자에게 MCP 설치를 요구하지 마세요"] } },

{ type:"table", title:"최종 체크리스트", head:["시점","할 일","확인"],
  rows:[
    ["<b>과정 전</b>","계정 7종 · Claude MAX 구독","로그인 되는지"],
    ["<b>과정 전</b>","런타임 4종 설치","버전 명령 4개 모두 출력"],
    ["<b>1일차 오전</b>","파이썬 패키지 + playwright chromium","오류 없이 완료"],
    ["<b>1일차 오전</b>","API 키·토큰 4종","파일에 저장 완료"],
    ["<b>1일차 오전</b>","브라우저 로그인 3종","창에서 직접 로그인"],
    ["<b>1일차 오후</b>","GitHub · Vercel 연결","배포 URL 열림"],
    ["<b>1일차 오후</b>","스킬 3폴더 설치 → 첫 실행","6채널 발행 성공"] ],
  note:"이 표를 인쇄해 옆에 두고 하나씩 지워가시면 빠짐이 없습니다." },

{ type:"closing", title:"준비가 끝나면, 이제 강의에만 집중하세요",
  sub:"오늘 강의는, 오늘 안에 끝납니다",
  items:[
    "카드뉴스 스타일 20종 → <a href='https://jj-aiedu.vercel.app/style/card-styles.html'>jj-aiedu.vercel.app/style/card-styles.html</a>",
    "과정 안내 → <a href='https://jj-aiedu.vercel.app/sns-automation'>jj-aiedu.vercel.app/sns-automation</a>",
    "교육 문의 → jjh@jjcreative.co.kr · 010-8448-2354",
    "JJ Creative 교육연구소"] },
];
